default_model_name: "paddleocr-vl-1.6"
default_model_size: "0.9b"

model_configs:
  paddleocr-vl-1.6:
    "0.9b":
      modelscope_repo: ["PaddlePaddle/PaddleOCR-VL-1.6"]
      model_name: "paddleocr-vl-1.6"
      model_size: "0.9b"
      ncore: 2
      quant_type: "w8a8h0_ssfp"
      context_length: "16k"
      ndevice: 1
      batch: 1
      prefill_length: 256
      max_size_w: 896
      max_size_h: 896
