#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/paddleocr_vl/modular_paddleocr_vl.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_paddleocr_vl.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2025 The PaddlePaddle Team and The HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modifications Copyright (c) 2026 HOUMO AI.
# Modified by HOUMO AI on 2026-08-20.
# Changes: Added configurable static output resolution and full-image output
# for the HMONNX visual graph, plus stretch/letterbox static resize.
# Original source: Hugging Face Transformers 5.15.0,
# src/transformers/models/paddleocr_vl/modular_paddleocr_vl.py.

import math
from collections.abc import Iterable

import numpy as np
from PIL import Image

from transformers.image_processing_backends import PilBackend
from transformers.image_processing_utils import BatchFeature
from transformers.image_utils import (
    OPENAI_CLIP_MEAN,
    OPENAI_CLIP_STD,
    ImageInput,
    PILImageResampling,
    SizeDict,
)

STATIC_SIZE_PAIR_ERROR = (
    "fixed_output_width and fixed_output_height must be set together"
)
from transformers.processing_utils import ImagesKwargs, Unpack
from transformers.utils import TensorType


class PaddleOCRVLImageProcessorKwargs(ImagesKwargs, total=False):
    r"""
    patch_size (`int`, *optional*, defaults to 14):
        The spatial patch size of the vision encoder.
    temporal_patch_size (`int`, *optional*, defaults to 1):
        The temporal patch size of the vision encoder.
    merge_size (`int`, *optional*, defaults to 2):
        The merge size of the vision encoder to llm encoder.
    """

    min_pixels: int
    max_pixels: int
    patch_size: int
    temporal_patch_size: int
    merge_size: int
    fixed_output_width: int
    fixed_output_height: int
    static_resize_mode: str


def smart_resize(
    height: int,
    width: int,
    factor: int = 28,
    min_pixels: int = 384 * 384,
    max_pixels: int = 1536 * 1536,
):
    if height < factor:
        width = round((width * factor) / height)
        height = factor

    if width < factor:
        height = round((height * factor) / width)
        width = factor

    if max(height, width) / min(height, width) > 200:
        raise ValueError(
            f"absolute aspect ratio must be smaller than 200, got {max(height, width) / min(height, width)}"
        )
    h_bar = round(height / factor) * factor
    w_bar = round(width / factor) * factor
    if h_bar * w_bar > max_pixels:
        beta = math.sqrt((height * width) / max_pixels)
        h_bar = max(factor, math.floor(height / beta / factor) * factor)
        w_bar = max(factor, math.floor(width / beta / factor) * factor)
    elif h_bar * w_bar < min_pixels:
        beta = math.sqrt(min_pixels / (height * width))
        h_bar = math.ceil(height * beta / factor) * factor
        w_bar = math.ceil(width * beta / factor) * factor
    return h_bar, w_bar


STATIC_RESIZE_MODES = ("stretch", "letterbox")


def _validate_static_size(width: int, height: int, patch_size: int, merge_size: int) -> None:
    if width <= 0 or height <= 0:
        raise ValueError(f"Invalid static output size: {(width, height)}")
    factor = patch_size * merge_size
    if width % factor != 0 or height % factor != 0:
        raise ValueError(
            f"Static output size {(width, height)} must be divisible by "
            f"patch_size * merge_size ({patch_size} * {merge_size} = {factor})"
        )


def _to_pil_image(image: np.ndarray) -> Image.Image:
    array = np.asarray(image)
    if array.ndim == 3 and array.shape[0] in (1, 3, 4) and array.shape[0] < array.shape[-1]:
        array = np.transpose(array, (1, 2, 0))
    if array.dtype != np.uint8:
        array = np.clip(np.rint(array), 0, 255).astype(np.uint8)
    if array.ndim == 2:
        return Image.fromarray(array, mode="L")
    if array.shape[-1] == 1:
        return Image.fromarray(array[..., 0], mode="L")
    if array.shape[-1] == 3:
        return Image.fromarray(array, mode="RGB")
    if array.shape[-1] == 4:
        return Image.fromarray(array, mode="RGBA").convert("RGB")
    raise ValueError(f"Unsupported image array shape: {array.shape}")


def resize_to_static_input(
    image: Image.Image,
    size: tuple[int, int],
    mode: str = "stretch",
) -> Image.Image:
    """Resize an RGB image to a fixed static input size.

    `stretch` uses BICUBIC and fills the target canvas without padding.
    `letterbox` uses LANCZOS, keeps the original aspect ratio, and centers
    the result on a white canvas.
    """
    if size is None:
        return image

    target_width, target_height = size
    if target_width <= 0 or target_height <= 0:
        raise ValueError(f"Invalid static input size: {size}")
    if image.mode != "RGB":
        image = image.convert("RGB")

    if mode == "stretch":
        return image.resize(size, Image.Resampling.BICUBIC)
    if mode != "letterbox":
        raise ValueError(f"Unsupported static resize mode: {mode}")

    scale = min(target_width / image.width, target_height / image.height)
    resized_size = (
        max(1, round(image.width * scale)),
        max(1, round(image.height * scale)),
    )
    resized = image.resize(resized_size, Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", size, "white")
    offset = (
        (target_width - resized.width) // 2,
        (target_height - resized.height) // 2,
    )
    canvas.paste(resized, offset)
    return canvas


class PaddleOCRVLImageProcessorPil(PilBackend):
    do_resize = True
    resample = PILImageResampling.BICUBIC
    size = {"shortest_edge": 384 * 384, "longest_edge": 1536 * 1536}
    default_to_square = False
    do_rescale = True
    do_normalize = True
    image_mean = OPENAI_CLIP_MEAN
    image_std = OPENAI_CLIP_STD
    do_convert_rgb = True
    patch_size = 14
    temporal_patch_size = 1
    merge_size = 2
    valid_kwargs = PaddleOCRVLImageProcessorKwargs
    model_input_names = ["pixel_values", "image_grid_thw"]
    static_resize_mode = "stretch"

    def __init__(
        self,
        fixed_output_width: int | None = None,
        fixed_output_height: int | None = None,
        static_resize_mode: str = "stretch",
        **kwargs: Unpack[PaddleOCRVLImageProcessorKwargs],
    ):
        # backward compatibility: override size with min_pixels and max_pixels if they are provided
        size = kwargs.pop("size", None)
        size = self.size if size is None else size
        if (min_pixels := kwargs.pop("min_pixels", None)) is not None:
            size["shortest_edge"] = min_pixels
            size.pop("min_pixels", None)
        if (max_pixels := kwargs.pop("max_pixels", None)) is not None:
            size["longest_edge"] = max_pixels
            size.pop("max_pixels", None)
        super().__init__(size=size, **kwargs)
        self.fixed_output_width = fixed_output_width
        self.fixed_output_height = fixed_output_height
        if fixed_output_width is not None or fixed_output_height is not None:
            if fixed_output_width is None or fixed_output_height is None:
                raise ValueError(STATIC_SIZE_PAIR_ERROR)
            _validate_static_size(
                fixed_output_width,
                fixed_output_height,
                self.patch_size,
                self.merge_size,
            )
        if static_resize_mode not in STATIC_RESIZE_MODES:
            raise ValueError(
                f"Unsupported static resize mode: {static_resize_mode}. "
                f"Expected one of {STATIC_RESIZE_MODES}"
            )
        self.static_resize_mode = static_resize_mode

    def _standardize_kwargs(
        self,
        size: int | Iterable[int] | dict[str, int] | SizeDict | None = None,
        min_pixels: int | None = None,
        max_pixels: int | None = None,
        **kwargs,
    ) -> dict:
        if min_pixels is not None and max_pixels is not None:
            size = SizeDict(shortest_edge=min_pixels, longest_edge=max_pixels)
        return super()._standardize_kwargs(size=size, **kwargs)

    def resize(
        self,
        image: np.ndarray,
        size: SizeDict,
        resample: "PILImageResampling | int | None",
        factor: int,
        **kwargs,
    ) -> np.ndarray:
        """Resize dynamically based on input image aspect ratio."""
        fixed_width = kwargs.pop("fixed_output_width", self.fixed_output_width)
        fixed_height = kwargs.pop("fixed_output_height", self.fixed_output_height)
        static_resize_mode = kwargs.pop("static_resize_mode", self.static_resize_mode)
        if fixed_width is not None or fixed_height is not None:
            if fixed_width is None or fixed_height is None:
                raise ValueError(STATIC_SIZE_PAIR_ERROR)
            _validate_static_size(fixed_width, fixed_height, self.patch_size, self.merge_size)
            if static_resize_mode not in STATIC_RESIZE_MODES:
                raise ValueError(
                    f"Unsupported static resize mode: {static_resize_mode}. "
                    f"Expected one of {STATIC_RESIZE_MODES}"
                )
            resized = resize_to_static_input(
                _to_pil_image(image),
                size=(int(fixed_width), int(fixed_height)),
                mode=static_resize_mode,
            )
            return np.transpose(np.asarray(resized, dtype=np.uint8), (2, 0, 1))
        if not size.shortest_edge or not size.longest_edge:
            raise ValueError(f"`size` dict must contain 'shortest_edge' and 'longest_edge' keys but got {size}.")

        height, width = image.shape[-2:]
        resized_height, resized_width = smart_resize(
            height,
            width,
            factor=factor,
            min_pixels=size.shortest_edge,
            max_pixels=size.longest_edge,
        )
        return super().resize(
            image=image,
            size=SizeDict(height=resized_height, width=resized_width),
            resample=resample,
        )

    def patchify(
        self,
        image: np.ndarray,
        patch_size: int,
        merge_size: int,
        temporal_patch_size: int,
    ) -> tuple[np.ndarray, int, int]:
        """Patchifies each image into flat layout of shape (`seq_len`, `patch_dim`) so we can concat dynamically shaped pixels."""
        # The exported visual graph consumes the normalized full image.
        image = np.asarray(image, dtype=np.float32)
        channel, resized_height, resized_width = image.shape
        grid_h, grid_w = resized_height // patch_size, resized_width // patch_size
        if temporal_patch_size != 1:
            raise ValueError("Static image input requires temporal_patch_size=1")
        if resized_height % patch_size or resized_width % patch_size:
            raise ValueError(
                f"Image size {resized_height}x{resized_width} is not divisible by "
                f"patch_size={patch_size}"
            )
        return image[None, ...], grid_h, grid_w

    def preprocess(
        self,
        images: ImageInput,
        **kwargs: Unpack[PaddleOCRVLImageProcessorKwargs],
    ) -> BatchFeature:
        return super().preprocess(images, **kwargs)

    def _preprocess(
        self,
        images: list[np.ndarray],
        do_resize: bool,
        size: SizeDict,
        resample: "PILImageResampling | None",
        do_rescale: bool,
        rescale_factor: float,
        do_normalize: bool,
        image_mean: float | list[float] | None,
        image_std: float | list[float] | None,
        patch_size: int,
        temporal_patch_size: int,
        merge_size: int,
        return_tensors: str | TensorType | None,
        **kwargs,
    ) -> BatchFeature:
        all_patches = []
        all_grids = []

        for image in images:
            if do_resize:
                image = self.resize(
                    image,
                    size=size,
                    resample=resample,
                    factor=patch_size * merge_size,
                )

            if do_rescale:
                image = self.rescale(image, rescale_factor)
            if do_normalize:
                image = self.normalize(image, image_mean, image_std)

            patches, grid_h, grid_w = self.patchify(
                image,
                patch_size=patch_size,
                merge_size=merge_size,
                temporal_patch_size=temporal_patch_size,
            )

            all_patches.append(patches)
            all_grids.append([1, grid_h, grid_w])

        pixel_values = np.concatenate(all_patches, axis=0)
        image_grid_thw = np.array(all_grids, dtype=np.int64)

        return BatchFeature(
            data={"pixel_values": pixel_values, "image_grid_thw": image_grid_thw}, tensor_type=return_tensors
        )

    def get_number_of_image_patches(self, height: int, width: int, images_kwargs: dict | None = None) -> int:
        """
        A utility that returns number of image patches for a given image size.

        Note: Do not remove this method! It is used by vLLM to infer the number of patches and placeholders
        without an image input.

        Args:
            height (`int`):
                Height of the input image.
            width (`int`):
                Width of the input image.
            images_kwargs (`dict`, *optional*)
                Any kwargs to override defaults of the image processor.
        Returns:
            `int`: Number of image patches per image.
        """
        images_kwargs = images_kwargs or {}
        fixed_width = images_kwargs.get("fixed_output_width", self.fixed_output_width)
        fixed_height = images_kwargs.get("fixed_output_height", self.fixed_output_height)
        static_resize_mode = images_kwargs.get("static_resize_mode", self.static_resize_mode)
        if static_resize_mode not in STATIC_RESIZE_MODES:
            raise ValueError(
                f"Unsupported static resize mode: {static_resize_mode}. "
                f"Expected one of {STATIC_RESIZE_MODES}"
            )
        if fixed_width is not None or fixed_height is not None:
            if fixed_width is None or fixed_height is None:
                raise ValueError(STATIC_SIZE_PAIR_ERROR)
            patch_size = images_kwargs.get("patch_size", self.patch_size)
            merge_size = images_kwargs.get("merge_size", self.merge_size)
            _validate_static_size(fixed_width, fixed_height, patch_size, merge_size)
            return (fixed_height // patch_size) * (fixed_width // patch_size)

        min_pixels = images_kwargs["min_pixels"] if "min_pixels" in images_kwargs else self.size["shortest_edge"]
        max_pixels = images_kwargs["max_pixels"] if "max_pixels" in images_kwargs else self.size["longest_edge"]
        patch_size = images_kwargs.get("patch_size", self.patch_size)
        merge_size = images_kwargs.get("merge_size", self.merge_size)

        factor = patch_size * merge_size
        resized_height, resized_width = smart_resize(
            height, width, factor, min_pixels=min_pixels, max_pixels=max_pixels
        )
        grid_h, grid_w = resized_height // patch_size, resized_width // patch_size
        return grid_h * grid_w


__all__ = ["PaddleOCRVLImageProcessorPil"]

