import os
import argparse
import json
import logging
from datetime import datetime
from typing import Tuple
import subprocess
from compiler_utils import (
    setup_logging,
    DockerExecutor,
    execute_cmd,
    compress_to_zip,
    delete_files,
    update_perf_file,
)


# Jfrog folder path
MODELZOO_URL = "http://10.10.1.53:8082/artifactory/AutoGeneratedModels"
RELEASE_MODELZOO_URL = "http://10.10.1.53:8082/artifactory/toolchain/release/models"
script_dir = os.path.dirname(os.path.abspath(__file__))
global logger
logger = logging.getLogger(__name__)


def parse_args():
    parser = argparse.ArgumentParser(description="Compile LLMs")
    parser.add_argument(
        "task_id",
        nargs='?',
        default=None,
        help="Task ID (optional positional argument)",
    )
    parser.add_argument(
        "-name",
        "--model_name",
        required=True,
        type=str,
        help="(required) model name, example: qwen3",
    )
    parser.add_argument(
        "-size",
        "--model_size",
        required=True,
        type=str,
        help="(required) model size, example: 8b, 14b",
    )
    parser.add_argument(
        "-v",
        "--version",
        required=True,
        type=str,
        help="Houmo Dadao software version, example: 0.3.0, 2.4.2",
    )
    parser.add_argument(
        "-t",
        "--target",
        type=str,
        default="xh2",
        help="Houmo backend, support: xh1, xh2.",
    )
    parser.add_argument(
        "-qm",
        "--quant_model_path",
        type=str,
        default="",
        help="Quantized model path, only support Jfrog url.",
    )
    parser.add_argument(
        "-pl",
        "--prefill_length",
        type=int,
        default=256,
        help="Prefill length, recommend to use the default value 256.",
    )
    parser.add_argument(
        "-cl",
        "--context_length",
        type=int,
        default=2048,
        help="Context length, default is 2048(2k).",
    )
    parser.add_argument(
        "-b",
        "--batch",
        type=int,
        default=1,
        help="batch number, default is 1.",
    )
    parser.add_argument(
        "-dn",
        "--device_num",
        type=int,
        default=1,
        help="The number of device, default is 1.",
    )
    parser.add_argument(
        "-cn",
        "--core_num",
        type=int,
        default=1,
        help="The number of core, default is 1. The maximum value is 4.",
    )
    parser.add_argument(
        "-j",
        "--j",
        type=int,
        default=24,
        help="the number of compilation threads, default is 24.",
    )
    parser.add_argument(
        "-up",
        "--upload",
        action="store_true",
        help="Upload quantized/compiled model to JFrog (default is False).",
    )
    parser.add_argument(
        "-del",
        "--delete_filetypes",
        nargs='+',
        type=str,
        default=[],
        help="List of file types to be deleted.",
    )
    parser.add_argument(
        "-r",
        "--result_dir",
        type=str,
        default="./",
        help="The path for storing the results.",
    )
    parser.add_argument(
        "-compile",
        "--forced_compile",
        action="store_true",
        help="Forced compilation (default is False).",
    )
    parser.add_argument(
        "-release",
        "--release",
        action="store_true",
        help="upload to jfrog release folder (default is False).",
    )
    parser.add_argument(
        "-perf",
        "--perf_config",
        type=str,
        default="",
        help="the path of perf config file.",
    )

    args = parser.parse_args()
    return args


def _get_jfrog_info(jfrog_url):
    import requests

    jfrog_base, jfrog_tail = jfrog_url.split("artifactory/")
    logger.info(f"_get_jfrog_info, jfrog_base: {jfrog_base}, jfrog_tail:{jfrog_tail}")
    jfrog_base = jfrog_base + "artifactory"
    file_info_path = f"{jfrog_base}/api/storage/{jfrog_tail}"
    response = requests.get(file_info_path)
    logger.info(
        f"_get_jfrog_info, ret: {response.status_code}, file_info_path:{file_info_path}"
    )
    if response.status_code == 200:
        return True

    return False


def _check_args(args: dict):
    from packaging import version

    # only support xh2 now
    if args.target not in ["xh1", "xh2"]:
        logger.error(f"Invalid houmo target {args.target}.")
        return False

    if (
        args.quant_model_path
        and "http" in args.quant_model_path
        and _get_jfrog_info(args.quant_model_path) is False
    ):
        logger.error(f"Invalid quant model path {args.quant_model_path}")
        return False

    if args.core_num <= 0 or args.core_num > 4:
        logger.error(f"Invalid core_num {args.core_num}, only supports [1, 4].")
        return False

    if args.device_num < -1 or args.device_num > 32:
        logger.error(f"Invalid device_num {args.device_num}, only supports [0, 32].")
        return False

    if args.batch < 0 or args.batch > 32:
        logger.error(f"Invalid batch number {args.batch}, only supports [1, 32].")
        return False

    try:
        xh1_min_ver = version.parse("2.4.2")
        xh2_min_ver = version.parse("0.3.0")
        ver = version.parse(args.version)
        if (args.target == "xh1" and ver < xh1_min_ver) or (
            args.target == "xh2" and ver < xh2_min_ver
        ):
            logger.error(f"Unsupported version {args.version} on {args.target}.")
            return False
    except version.InvalidVersion as e:
        logger.error(f"Invalid version {args.version}, error msg: {str(e)}")
        return False

    if args.context_length > 0 and args.context_length % 128 != 0:
        logger.error(
            f"Invalid context_length {args.context_length}, it needs to be divisible by 1024."
        )
        return False

    logger.info(
        "\n***** Compilation Configs *****\n"
        "-- Model name: %s \n"
        "-- Model size: %s \n"
        "-- DaDao Software version: %s \n"
        "-- Quantized model path: %s \n"
        "-- Prefill length: %d \n"
        "-- Context length: %d \n"
        "-- Houmo target: %s \n"
        "-- Batch: %d \n"
        "-- Device num: %d \n"
        "-- Core num: %d \n"
        "-- J: %d \n"
        "-- Save results to %s\n"
        "-- Task Id: %s \n",
        args.model_name,
        args.model_size,
        args.version,
        args.quant_model_path,
        args.prefill_length,
        args.context_length,
        args.target,
        args.batch,
        args.device_num,
        args.core_num,
        args.j,
        args.result_dir,
        args.task_id,
    )

    return True


def _upload_model(
    date_str: str,
    model_name: str,
    model_file: str,
    file_name: str,
    local_md5: str,
    log_file: str,
    version_str: str,
) -> str:
    import requests

    jfrog_repo_url = MODELZOO_URL
    jfrog_suffix = f"{model_name}/{date_str}/{file_name}"
    jfrog_pwd = "modelrobot:123@abAB"
    if version_str:
        jfrog_repo_url = RELEASE_MODELZOO_URL
        jfrog_suffix = f"{version_str}/{model_name}/{file_name}"
        jfrog_pwd = "public:Password@123"

    jfrog_file_path = f"{jfrog_repo_url}/{jfrog_suffix}"
    jfrog_base, jfrog_tail = jfrog_repo_url.split("artifactory/")
    jfrog_base = jfrog_base + "artifactory"
    file_info_path = f"{jfrog_base}/api/storage/{jfrog_tail}/{jfrog_suffix}"
    response = requests.get(file_info_path)
    if response.status_code == 200:
        url_md5 = response.json()['checksums']['md5']
        if local_md5 == url_md5:
            logger.info(f"{jfrog_file_path} ({url_md5}) already exists.")
            return jfrog_file_path

    cmds = ["curl", "-u", jfrog_pwd, "-T", model_file, jfrog_file_path]
    ret = execute_cmd(cmds, log_file)
    if not ret:
        logger.error(f"Upload model zipped file {model_file} failed.")
        return None

    # upload cpp file
    cpp_zip_file = model_file[:-4] + "_cpps.zip"
    if os.path.exists(cpp_zip_file):
        jfrog_cpp_zip_path = jfrog_file_path[:-4] + "_cpps.zip"
        if version_str:
            jfrog_cpp_zip_path = jfrog_cpp_zip_path.replace(
                "/release/models/", "/release/models_outdated/"
            )
        cmds = [
            "curl",
            "-u",
            jfrog_pwd,
            "-T",
            cpp_zip_file,
            jfrog_cpp_zip_path,
        ]
        ret = execute_cmd(cmds, log_file)
        if not ret:
            logger.error(f"Upload cpp zipped file {cpp_zip_file} failed.")
            return None

    return jfrog_file_path


def _get_md5sum(model_file):
    if not os.path.isfile(model_file):
        logger.error(f"Error: {model_file} not exist.")
        return None

    try:
        result = subprocess.run(
            ['md5sum', model_file],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        md5_sum = result.stdout.split()[0]
        return md5_sum

    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to execute md5sum: {e.stderr}")
        return None
    except Exception as e:
        logger.error(f"Unknown error: {str(e)}")
        return None


def _update_model_table(new_model):
    import pandas as pd

    model_csv = f"{script_dir}/published_models.csv"
    try:
        model_df = pd.read_csv(model_csv)
        target_md5 = new_model["model_md5sum"]
        target_jfrog_path = new_model["model_path"]
        condition_contains = model_df['model_path'].str.contains(
            target_jfrog_path, na=False
        )
        condition_md5_mismatch = model_df['model_md5sum'] != target_md5
        rows_to_delete = condition_contains & condition_md5_mismatch
        model_df = model_df[~rows_to_delete]

        new_model_df = pd.DataFrame(new_model, index=[0])
        model_df = pd.concat([model_df, new_model_df], ignore_index=True)
        model_df.to_csv(model_csv, index=False)
        logger.info(f"Append a new model {new_model} into {model_csv}.")
        return True
    except Exception as e:
        logger.error(f"Error occurred: {str(e)}")
    return False


def _publish_model(
    date_str: str,
    model_file_name: str,
    host_model_dir: str,
    host_result_dir: str,
    model_name: str,
    host_log_file: str,
    version_str: str = None,
    extensions: list = list(),
) -> Tuple[str, str]:
    compressed_model = f"{host_result_dir}/{model_file_name}"
    if os.path.exists(compressed_model):
        logger.warning(
            f"The compressed model file already exists. Please clean it up first: {compressed_model}"
        )
    else:
        logger.info(f"Compress model folder {host_model_dir} -> {compressed_model}")
        ret = compress_to_zip(host_model_dir, compressed_model, extensions)
        if ret is False:
            return None, None
    model_md5 = _get_md5sum(compressed_model)
    model_jfrog_path = _upload_model(
        date_str,
        model_name,
        compressed_model,
        model_file_name,
        model_md5,
        host_log_file,
        version_str,
    )
    logger.info(f"Publish info: Jfrog path: {model_jfrog_path}, md5sum: {model_md5}")

    return model_md5, model_jfrog_path


if __name__ == "__main__":
    args = parse_args()

    task_id = args.task_id
    host_result_dir = args.result_dir
    os.makedirs(host_result_dir, exist_ok=True)
    log_dir = host_result_dir + "/logs"
    os.makedirs(log_dir, exist_ok=True)
    host_log_file, ts_str = setup_logging(log_dir)
    logger = logging.getLogger(__name__)
    logger.info(f"##hm result_dir is:{host_result_dir}")

    # check the validity of parameters
    if _check_args(args) is False:
        exit(1)
    # load parameters
    model_name = args.model_name
    model_size = args.model_size
    quant_model_path = args.quant_model_path
    target = args.target
    version = args.version
    prefill_len = args.prefill_length
    context_len = args.context_length
    device_num = args.device_num
    core_num = args.core_num
    batch = args.batch
    j = args.j

    model_name_ori = model_name

    # get the information of supported models
    with open("./supported_models.json", 'r', encoding='utf-8') as md_file:
        model_info = json.load(md_file)
    try:
        if model_name not in model_info:
            logger.error(f"Unsupport model {model_name}.")
            exit(2)
        if model_size not in model_info[model_name]:
            logger.error(f"Unsupport model size {model_name} {model_size}.")
            exit(2)
        if target not in model_info[model_name][model_size]["support_backends"]:
            logger.error(f"{model_name} {model_size} does not support {target}.")
            exit(2)
        model_dir = model_info[model_name][model_size]["path"]  # releative path
        raw_model_path = model_info[model_name][model_size]["raw"]  # releative path
    except Exception as e:
        logger.error(
            f"Unsupported model {model_name} {model_size}, error msg: {str(e)}"
        )
        exit(2)

    # create a result folder for the current container
    if args.task_id:
        container_name = f"compiler_{target}_{version}_{task_id}"
        logger.info(f"start container with task_id:{task_id} in name:{container_name} ")
    else:
        container_name = f"compiler_{target}_{version}_{ts_str}"
    host_result_dir += f"/{container_name}"
    os.makedirs(host_result_dir, exist_ok=True)

    host_quant_model = (
        f"{host_result_dir}/quant_results"
        if "http" in quant_model_path
        else quant_model_path
    )
    logger.info(f"##hm host_quant_model is:{host_quant_model}")
    if not quant_model_path:
        quant_flag = True
    else:
        quant_flag = False
        os.makedirs(host_quant_model, exist_ok=True)

    ###### Docker Executor ######
    # The folder that stores the original model structure and weights (10.64.35.39)
    host_model_zoo = "/data/gexinyu_workspace/modelzoo"
    # construct docker image name
    system = "ubuntu20.04" if target == "xh1" else "ubuntu24.04"
    image_name = f"harbor.houmo.ai/toolchain/release:Dadao-{target}-v{version}-{system}-x86.64.latest"
    # set container configs
    container_home = "/hmdd"
    container_result_dir = f"{container_home}/results"
    container_log_file = container_home + "/logs/" + host_log_file.rsplit("/", 1)[-1]
    # construct the commands to be executed in the container
    commands = ["echo 'Hi LLM Compiler!'"]
    if quant_flag:
        # quant command
        container_quant_res = f"{container_result_dir}/quant_results"
        quant_cmd = f"python3 execute_quantization.py -t {target} -m {model_dir} -n {model_name} -raw {raw_model_path} -b {batch} -pl {prefill_len} -cl {context_len} -r {container_quant_res} -log {container_log_file}"
        commands.append(
            f"cd {container_home}/imodelzoo/service/llm_compiler && {quant_cmd}"
        )
        quant_model = f"{container_quant_res}/hmquant"
    else:
        quant_model = f"{container_home}/quant_model"
        check_cmd = f"python3 check_quant_folder.py -n {model_name} -qm {quant_model} -path {quant_model_path}"
        commands.append(
            f"cd {container_home}/imodelzoo/service/llm_compiler && {check_cmd}"
        )

    if args.forced_compile or not quant_flag:
        # compile command
        container_compile_res = f"{container_result_dir}/compile_results"
        compile_cmd = f"python3 execute_compilation.py -n {model_name} -m {model_dir} -qm {quant_model} "
        if context_len >= 128:
            compile_cmd += f"-cl {context_len} "
        if device_num >= 0:
            compile_cmd += f"-dn {device_num} "
        if batch > 0:
            compile_cmd += f"-b {batch} "
        if core_num > 0:
            compile_cmd += f"-cn {core_num} "
        compile_cmd += f"-j {j} -r {container_compile_res} -log {container_log_file}"
        commands.append(
            f"cd {container_home}/imodelzoo/service/llm_compiler && {compile_cmd}"
        )

    # create a docker executor
    docker_exec = DockerExecutor(
        image=image_name,
        container_name=container_name,
        host_log_path=host_log_file,
        container_workdir=container_home,
        keep_container=False,
    )
    docker_flag = True
    try:
        docker_exec.pull_image()
        # map the current directory of the host to the container
        volumes = {
            # map imodelzoo folder
            os.path.abspath(f"{script_dir}/../../"): {
                "bind": f"{container_home}/imodelzoo",
                "mode": "rw",
            },
            # map original models folder
            host_model_zoo: {
                "bind": "/modelzoo",
                "mode": "rw",
            },
            # map results folder
            os.path.abspath(host_result_dir): {
                "bind": container_result_dir,
                "mode": "rw",
            },
            # map logs folder
            os.path.abspath(log_dir): {
                "bind": f"{container_home}/logs",
                "mode": "rw",
            },
        }
        if quant_flag:
            gpu_env = {
                "NVIDIA_VISIBLE_DEVICES": "all",  # 可见所有GPU
                "NVIDIA_DRIVER_CAPABILITIES": "compute,utility",  # GPU能力
            }
            docker_exec.start_container(
                volumes=volumes, environment=gpu_env, task_id=args.task_id
            )
        else:
            volumes[os.path.abspath(host_quant_model)] = {
                "bind": f"{container_home}/quant_model",
                "mode": "rw",
            }
            docker_exec.start_container(volumes=volumes, task_id=args.task_id)
        cmds_res = docker_exec.execute_commands(commands, stop_on_error=True)
        for res in cmds_res:
            if res.get("exit_code", -1) != 0:
                logger.info(f"##hm docker_exec commands error occured")
                docker_flag = False
                break
    except Exception as e:
        docker_flag = False
        logger.error(f"Error occurred: {str(e)}")
    finally:
        docker_exec.stop_and_remove_container()

    jfrog_path_quant = (
        args.quant_model_path if "http" in args.quant_model_path else None
    )
    md5sum_quant = None
    compiled_file_name = None
    context_str = (
        str(int(context_len / 1024)) + "k"
        if context_len >= 1024
        else f"{(context_len/1024)}k"
    )
    chip_str = f"{device_num}chips" if device_num > 1 else "1chip"
    core_str = f"{core_num}cores" if core_num > 1 else f"{core_num}core"

    if docker_flag and args.upload is True:
        version_str = f"{target}-v{version}" if args.release is True else ""
        if version_str:
            model_name = "deepseek" if "deepseek" in model_name else model_name
        current_dt = datetime.now()
        current_ts = (
            current_dt.strftime("%Y%m%d_%H%M%S") if not version_str else f"v{version}"
        )
        today = current_dt.strftime("%Y%m%d")
        if quant_flag:
            # publish quantized model (will upload to Jfrog)
            host_quant_dir = host_result_dir + "/quant_results/hmquant"
            quant_file_name = f"hmquant_{target}_{model_name}_{model_size}_"
            if prefill_len > 0:
                quant_file_name += f"{prefill_len}_"
            if context_len > 0:
                quant_file_name += f"{context_str}_"
            quant_file_name += f"{current_ts}.zip"

            md5sum_quant, jfrog_path_quant = _publish_model(
                today,
                quant_file_name,
                host_quant_dir,
                host_result_dir,
                model_name,
                host_log_file,
                version_str,
            )
            if jfrog_path_quant is None or md5sum_quant is None:
                logger.error(f"Failed to publish quant model {host_quant_dir}.")
                exit(44)
            else:
                logger.info(
                    f"#hm upload to jfrog success with quantpath:{jfrog_path_quant}"
                )
        elif jfrog_path_quant:
            compressed_quant_file = (
                f"{host_result_dir}/quant_results/"
                + quant_model_path.rsplit("/", 1)[-1]
            )
            md5sum_quant = _get_md5sum(compressed_quant_file)

        # 非quant的时候，才上传build后的文件
        if args.forced_compile or not quant_flag:
            # publish compiled model (will upload to Jfrog)
            host_compile_dir = host_result_dir + "/compile_results"
            compiled_file_name = f"hmm_{target}_{model_name}_{model_size}_"
            if prefill_len > 0:
                compiled_file_name += f"{prefill_len}_"
            if context_len > 0:
                compiled_file_name += f"{context_str}_"
            if batch > 0:
                compiled_file_name += f"b{batch}_"
            compiled_file_name += f"{chip_str}_{core_str}_{current_ts}.zip"
            md5sum_compile, jfrog_path_compile = _publish_model(
                today,
                compiled_file_name,
                host_compile_dir,
                host_result_dir,
                model_name,
                host_log_file,
                version_str,
                [".hmm", ".hmms", ".pt"],
            )
            if jfrog_path_compile is None or md5sum_compile is None:
                logger.error(f"Failed to publish compiled model {host_compile_dir}.")
                exit(4)
            else:
                logger.info(
                    f"#hm upload to jfrog success with path:{jfrog_path_compile}"
                )

            # update published model table: published_models.csv
            publish_dt = current_dt.strftime("%Y%m%d %H:%M:%S")
            model_id = f"{os.getpid()}-{current_ts}"
            version_str = f"v{version}"
            new_model = {
                "model_id": model_id,
                "model_name": model_name,
                "model_size": model_size,
                "prefill_length": prefill_len,
                "context_length": context_len,
                "version": version_str,
                "target": target,
                "device_num": device_num,
                "core_num": core_num,
                "publish_time": publish_dt,
                "model_md5sum": md5sum_compile,
                "quant_model_md5sum": md5sum_quant,
                "model_path": jfrog_path_compile,
                "quant_model_path": jfrog_path_quant,
            }
            ret = _update_model_table(new_model)
            if ret is False:
                logger.info(f"##hm enter here5")
                exit(5)

    if (
        args.perf_config
        and target == "xh2"
        and device_num <= 2
        and model_info[model_name_ori][model_size]["perf"] is True
    ):
        if compiled_file_name is None:
            compiled_file_name = f"{target}_{model_name}_{model_size}_"
            if prefill_len > 0:
                compiled_file_name += f"{prefill_len}_"
            if context_len > 0:
                compiled_file_name += f"{context_str}_"
            if batch > 0:
                compiled_file_name += f"b{batch}_"
            compiled_file_name += f"{chip_str}_{core_str}_v{version}"

        new_stream = {
            "ModelName": compiled_file_name,
            "prefill": f"{host_result_dir}/compile_results/{model_name}_prefill.hmm",
            "decode": f"{host_result_dir}/compile_results/{model_name}_decode.hmm",
            "embedding": f"{host_result_dir}/compile_results/hmquant/quant_embedding.bin",
            "input": 256,
            "stop": 2048,
            "ndevices": device_num if device_num > 1 else 1,
            "loop": 2,
            "batch": batch,
        }
        if context_len < (2048 + 256) and context_len >= (1024 + 256):
            new_stream["stop"] = 1024
        elif context_len > 0 and context_len < (1024 + 256):
            new_stream["input"] = int(context_len * 0.2)
            new_stream["stop"] = context_len - new_stream["input"]
        if "-vl" in model_name_ori:
            new_stream["visual"] = (
                f"{host_result_dir}/compile_results/{model_name}_visual.hmm",
            )
        if device_num > 1:
            new_stream["prefill"] = new_stream["prefill"] + "s"
            new_stream["decode"] = new_stream["decode"] + "s"
            if "visual" in new_stream:
                new_stream["visual"] = new_stream["visual"] + "s"

        cfg_path = args.perf_config
        if os.path.exists(cfg_path):
            try:
                with open(cfg_path, "r", encoding="utf-8") as f:
                    cfg_data = json.load(f)
            except json.JSONDecodeError:
                logger.error(f"错误：{cfg_path} 不是合法的 JSON 文件，将创建新文件")
                cfg_data = {"Streams": []}
        else:
            logger.error(f"提示：{cfg_path} 不存在，将创建新文件")
            cfg_data = {"Streams": []}

        if "Streams" not in cfg_data or not isinstance(cfg_data["Streams"], list):
            logger.warning("警告：JSON 结构异常，重置 Streams 为列表")
            cfg_data["Streams"] = []

        cfg_data["Streams"].append(new_stream)

        with open(cfg_path, "w", encoding="utf-8") as f:
            json.dump(cfg_data, f, indent=2, ensure_ascii=False, sort_keys=False)
        logger.info(f"成功追加配置！当前待 Perf 模型总数：{len(cfg_data['Streams'])}")

    del_suffixes = args.delete_filetypes
    delete_files(host_result_dir, [".zip"])
    if len(del_suffixes) > 0:
        logger.info(f"Start to clear result files {del_suffixes}")
        delete_files(host_result_dir, del_suffixes)
        quant_work_dir = f"{script_dir}/../../{model_dir}/work_dirs"
        if os.path.exists(quant_work_dir):
            delete_files(quant_work_dir, del_suffixes)

    if not docker_flag:
        logger.info("### something error in docker container")
        exit(-1)
