# Copyright 2025 HOUMO AI
#
# File: compile_llms.py
# Description:
#   Compile Large Language Models (LLMs) for deployment on Houmo hardware platforms.
#   This script orchestrates the entire compilation pipeline including quantization,
#   model compilation, result publishing, and performance configuration updates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

import os
import glob
import argparse
import requests
import json
import logging
from datetime import datetime
from typing import Tuple
import subprocess
from compiler_utils import (
    setup_logging,
    DockerExecutor,
    execute_cmd,
    compress_to_zip,
    delete_files,
)


# Jfrog folder path
MODELZOO_URL = "http://artifactory.houmo.ai/artifactory/AutoGeneratedModels"
RELEASE_MODELZOO_URL = "http://artifactory.houmo.ai/artifactory/Dadao/models"
script_dir = os.path.dirname(os.path.abspath(__file__))
logger = logging.getLogger(__name__)

JFROG_CREDENTIALS_RELEASE = os.getenv("JFROG_CREDENTIALS_RELEASE")
JFROG_CREDENTIALS_GENMDS = os.getenv("JFROG_CREDENTIALS_GENMDS")


def parse_args():
    """Parse command line arguments for the LLM compilation script."""
    parser = argparse.ArgumentParser(description="Compile LLMs")
    parser.add_argument(
        "task_id",
        nargs="?",
        default=None,
        help="Task ID (optional positional argument)",
    )
    parser.add_argument(
        "-name",
        "--model_name",
        required=True,
        type=str,
        help="(required) model name, example: qwen3",
    )
    parser.add_argument(
        "-size",
        "--model_size",
        required=True,
        type=str,
        help="(required) model size, example: 8b, 14b",
    )
    parser.add_argument(
        "-v",
        "--version",
        required=True,
        type=str,
        help="Houmo Dadao software version, example: 0.3.0, 2.4.2",
    )
    parser.add_argument(
        "-t",
        "--target",
        type=str,
        default="xh2",
        help="Houmo backend, support: xh1, xh2.",
    )
    parser.add_argument(
        "-qm",
        "--quant_model_path",
        type=str,
        default="",
        help="Quantized model path, only support Jfrog url.",
    )
    parser.add_argument(
        "-pl",
        "--prefill_length",
        type=int,
        default=256,
        help="Prefill length, recommend to use the default value 256.",
    )
    parser.add_argument(
        "-cl",
        "--context_length",
        type=int,
        default=2048,
        help="Context length, default is 2048(2k).",
    )
    parser.add_argument(
        "-b",
        "--batch",
        type=int,
        default=1,
        help="batch number, default is 1.",
    )
    parser.add_argument(
        "-dn",
        "--device_num",
        type=int,
        default=1,
        help="The number of device, default is 1.",
    )
    parser.add_argument(
        "-cn",
        "--core_num",
        type=int,
        default=1,
        help="The number of core, default is 1. The maximum value is 4.",
    )
    parser.add_argument(
        "-j",
        "--j",
        type=int,
        default=24,
        help="the number of compilation threads, default is 24.",
    )
    parser.add_argument(
        "-up",
        "--upload",
        action="store_true",
        help="Upload quantized/compiled model to JFrog (default is False).",
    )
    parser.add_argument(
        "-del",
        "--delete_filetypes",
        nargs="+",
        type=str,
        default=[],
        help="List of file types to be deleted.",
    )
    parser.add_argument(
        "-r",
        "--result_dir",
        type=str,
        default="./",
        help="The path for storing the results.",
    )
    parser.add_argument(
        "-compile",
        "--forced_compile",
        action="store_true",
        help="Forced compilation (default is False).",
    )
    parser.add_argument(
        "-release",
        "--release",
        action="store_true",
        help="upload to jfrog release folder (default is False).",
    )
    parser.add_argument(
        "-perf",
        "--perf_config",
        type=str,
        default="",
        help="the path of perf config file.",
    )
    parser.add_argument(
        "--flash_attention",
        type=int,
        default=-1,
        choices=[-1, 0, 1, 2, 3],
        help="flash attention optimization",
    )
    parser.add_argument(
        "--strip",
        type=str,
        default="off",
        choices=["off", "overwrite", "copy"],
        help="Strip shared weights from the last input model",
    )

    args = parser.parse_args()
    return args


def _get_jfrog_info(jfrog_url) -> bool:
    """Check if a JFrog URL is accessible.

    Args:
        jfrog_url (str): URL to check

    Returns:
        bool: True if accessible, False otherwise
    """

    jfrog_base, jfrog_tail = jfrog_url.split("artifactory/")
    logger.info(f"_get_jfrog_info, jfrog_base: {jfrog_base}, jfrog_tail:{jfrog_tail}")
    jfrog_base = jfrog_base + "artifactory"
    file_info_path = f"{jfrog_base}/api/storage/{jfrog_tail}"
    response = requests.get(file_info_path)
    logger.info(
        f"_get_jfrog_info, ret: {response.status_code}, file_info_path:{file_info_path}"
    )
    if response.status_code == 200:
        return True

    return False


def _check_args(args: dict) -> bool:
    """Validate the provided command line arguments.

    Args:
        args: Arguments object containing parsed command line options

    Returns:
        bool: True if arguments are valid, False otherwise
    """
    from packaging import version

    if args.target not in ["xh1", "xh2"]:
        logger.error(f"Invalid houmo target {args.target}.")
        return False

    if (
        args.quant_model_path
        and "http" in args.quant_model_path
        and _get_jfrog_info(args.quant_model_path) is False
    ):
        logger.error(f"Invalid quant model path {args.quant_model_path}")
        return False

    if args.core_num <= 0 or args.core_num > 4:
        logger.error(f"Invalid core_num {args.core_num}, only supports [1, 4].")
        return False

    if args.device_num < -1 or args.device_num > 32:
        logger.error(f"Invalid device_num {args.device_num}, only supports [0, 32].")
        return False

    if args.batch < 0 or args.batch > 32:
        logger.error(f"Invalid batch number {args.batch}, only supports [1, 32].")
        return False

    try:
        xh1_min_ver = version.parse("2.4.2")
        xh2_min_ver = version.parse("0.3.0")
        ver = version.parse(args.version)
        if (args.target == "xh1" and ver < xh1_min_ver) or (
            args.target == "xh2" and ver < xh2_min_ver
        ):
            logger.error(f"Unsupported version {args.version} on {args.target}.")
            return False
    except version.InvalidVersion as e:
        logger.error(f"Invalid version {args.version}, error msg: {str(e)}")
        return False

    if args.context_length > 0 and args.context_length % 128 != 0:
        logger.error(
            f"Invalid context_length {args.context_length}, it needs to be divisible by 1024."
        )
        return False

    logger.info(
        "\n***** Compilation Configs *****\n"
        "-- Model name: %s \n"
        "-- Model size: %s \n"
        "-- DaDao Software version: %s \n"
        "-- Quantized model path: %s \n"
        "-- Prefill length: %d \n"
        "-- Context length: %d \n"
        "-- Houmo target: %s \n"
        "-- Batch: %d \n"
        "-- Device num: %d \n"
        "-- Core num: %d \n"
        "-- J: %d \n"
        "-- Flash Attention: %d \n"
        "-- Save results to %s\n"
        "-- Task Id: %s \n",
        args.model_name,
        args.model_size,
        args.version,
        args.quant_model_path,
        args.prefill_length,
        args.context_length,
        args.target,
        args.batch,
        args.device_num,
        args.core_num,
        args.j,
        args.flash_attention,
        args.result_dir,
        args.task_id,
    )

    return True


def _upload_model(
    date_str: str,
    model_name: str,
    model_file: str,
    file_name: str,
    local_md5: str,
    log_file: str,
    version_str: str,
) -> None | str:
    """Upload a model file to JFrog repository.

    Uploads the specified model file to the JFrog repository with MD5 checksum
    verification to prevent duplicate uploads. Also uploads associated CPP zip file
    if it exists.

    Args:
        date_str (str): Date string for organizing uploads
        model_name (str): Name of the model
        model_file (str): Path to the local model file
        file_name (str): Name to use for the uploaded file
        local_md5 (str): MD5 checksum of the local file
        log_file (str): Path to the log file
        version_str (str): Version string for release uploads

    Returns:
        str: JFrog path of the uploaded model, or None if upload failed
    """

    if not JFROG_CREDENTIALS_RELEASE and not JFROG_CREDENTIALS_GENMDS:
        logger.error(
            "Missing required JFrog credentials environment variables!\n"
            "Please set:\n"
            "  - JFROG_CREDENTIALS_RELEASE (format: username:password)\n"
            "  - JFROG_CREDENTIALS_GENMDS (format: username:password)"
        )
        return None

    # Select JFrog credentials and repository path based on version flag
    if version_str:
        jfrog_repo_url = RELEASE_MODELZOO_URL
        jfrog_suffix = f"{version_str}/{model_name}/{file_name}"
        jfrog_credentials = JFROG_CREDENTIALS_RELEASE
    else:
        jfrog_repo_url = MODELZOO_URL
        jfrog_suffix = f"{model_name}/{date_str}/{file_name}"
        jfrog_credentials = JFROG_CREDENTIALS_GENMDS

    # Construct full JFrog file path and API path for MD5 check
    jfrog_file_path = f"{jfrog_repo_url}/{jfrog_suffix}"
    try:
        # Split JFrog URL to build storage API path (handle edge cases)
        jfrog_base, jfrog_tail = jfrog_repo_url.split("artifactory/")
        jfrog_base = f"{jfrog_base}artifactory"
        file_info_path = f"{jfrog_base}/api/storage/{jfrog_tail}/{jfrog_suffix}"
    except ValueError as e:
        logger.error(
            f"Invalid JFrog repository URL format: {jfrog_repo_url}. Error: {e}"
        )
        return None

    # Check if file already exists in JFrog (MD5 verification)
    try:
        response = requests.get(file_info_path, timeout=10)
        response.raise_for_status()  # Raise exception for HTTP errors

        url_md5 = response.json()["checksums"]["md5"]
        if local_md5 == url_md5:
            logger.info(f"{jfrog_file_path} ({url_md5}) already exists. Skip upload.")
            return jfrog_file_path
    except requests.exceptions.RequestException as e:
        # Ignore 404 (file not found) - proceed to upload
        if response.status_code != 404:
            logger.warning(
                f"Failed to check existing file in JFrog: {e}. Proceeding to upload."
            )
    except KeyError as e:
        logger.error(
            f"Invalid response format from JFrog API (missing {e}). Proceeding to upload."
        )

    # Upload main model file
    upload_cmds = ["curl", "-u", jfrog_credentials, "-T", model_file, jfrog_file_path]
    if not execute_cmd(upload_cmds, log_file):
        logger.error(f"Failed to upload model file: {model_file}")
        return None

    # Upload associated CPP zip file (if exists)
    cpp_zip_file = f"{model_file[:-4]}_cpps.zip"
    if os.path.exists(cpp_zip_file):
        jfrog_cpp_zip_path = f"{jfrog_file_path[:-4]}_cpps.zip"

        # Adjust path for release version CPP files
        if version_str:
            jfrog_cpp_zip_path = jfrog_cpp_zip_path.replace(
                "/Dadao/models/", "/toolchain/release/models_outdated/"
            )

        # Execute CPP file upload
        cpp_upload_cmds = [
            "curl",
            "-u",
            jfrog_credentials,
            "-T",
            cpp_zip_file,
            jfrog_cpp_zip_path,
        ]
        if not execute_cmd(cpp_upload_cmds, log_file):
            logger.error(f"Failed to upload CPP zip file: {cpp_zip_file}")
            return None

    return jfrog_file_path


def _get_md5sum(model_file):
    """Calculate the MD5 checksum of a file.

    Args:
        model_file (str): Path to the file to check

    Returns:
        str: MD5 checksum of the file, or None if calculation failed
    """
    if not os.path.isfile(model_file):
        logger.error(f"Error: {model_file} not exist.")
        return None

    try:
        result = subprocess.run(
            ["md5sum", model_file],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        md5_sum = result.stdout.split()[0]
        return md5_sum

    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to execute md5sum: {e.stderr}")
        return None
    except Exception as e:
        logger.error(f"Unknown error: {str(e)}")
        return None


def _update_model_table(new_model) -> bool:
    """Update the published models table with new model information.

    Adds the new model entry to the published models CSV file, updating existing
    entries with the same path but different MD5 checksums.

    Args:
        new_model (dict): Dictionary containing model metadata

    Returns:
        bool: True if update was successful, False otherwise
    """
    import pandas as pd

    model_csv = f"{script_dir}/published_models.csv"
    try:
        model_df = pd.read_csv(model_csv)
        target_md5 = new_model["model_md5sum"]
        target_jfrog_path = new_model["model_path"]
        condition_contains = model_df["model_path"].str.contains(
            target_jfrog_path, na=False
        )
        condition_md5_mismatch = model_df["model_md5sum"] != target_md5
        rows_to_delete = condition_contains & condition_md5_mismatch
        model_df = model_df[~rows_to_delete]

        new_model_df = pd.DataFrame(new_model, index=[0])
        model_df = pd.concat([model_df, new_model_df], ignore_index=True)
        model_df.to_csv(model_csv, index=False)
        logger.info(f"Append a new model {new_model} into {model_csv}.")
        return True
    except Exception as e:
        logger.error(f"Error occurred: {str(e)}")
    return False


def _publish_model(
    date_str: str,
    model_file_name: str,
    host_model_dir: str,
    host_result_dir: str,
    model_name: str,
    host_log_file: str,
    version_str: str = None,
    extensions: list = list(),
) -> Tuple[str, str]:
    """Publish a model by compressing and uploading it to JFrog.

    Compresses the model directory into a ZIP file, calculates its MD5 checksum,
    and uploads it to the JFrog repository.

    Args:
        date_str (str): Date string for organizing uploads
        model_file_name (str): Name for the compressed model file
        host_model_dir (str): Directory containing the model to publish
        host_result_dir (str): Directory to store the compressed file
        model_name (str): Name of the model
        host_log_file (str): Path to the log file
        version_str (str): Version string for release uploads
        extensions (list): List of file extensions to include in compression

    Returns:
        Tuple[str, str]: MD5 checksum and JFrog path of the published model,
                         or (None, None) if publication failed
    """
    compressed_model = f"{host_result_dir}/{model_file_name}"
    if os.path.exists(compressed_model):
        logger.warning(
            f"The compressed model file already exists. Please clean it up first: {compressed_model}"
        )
    else:
        logger.info(f"Compress model folder {host_model_dir} -> {compressed_model}")
        ret = compress_to_zip(host_model_dir, compressed_model, extensions)
        if ret is False:
            return None, None
    model_md5 = _get_md5sum(compressed_model)
    model_jfrog_path = _upload_model(
        date_str,
        model_name,
        compressed_model,
        model_file_name,
        model_md5,
        host_log_file,
        version_str,
    )
    logger.info(f"Publish info: Jfrog path: {model_jfrog_path}, md5sum: {model_md5}")

    return model_md5, model_jfrog_path


if __name__ == "__main__":
    args = parse_args()

    task_id = args.task_id
    host_result_dir = args.result_dir
    os.makedirs(host_result_dir, exist_ok=True)
    log_dir = host_result_dir + "/logs"
    os.makedirs(log_dir, exist_ok=True)
    host_log_file, ts_str = setup_logging(log_dir)
    logger = logging.getLogger(__name__)
    logger.info(f"##hm result_dir is:{host_result_dir}")

    # Check the validity of parameters
    if _check_args(args) is False:
        exit(1)
    # Load parameters
    model_name = args.model_name
    model_size = args.model_size
    quant_model_path = args.quant_model_path
    target = args.target
    version = args.version
    prefill_len = args.prefill_length
    context_len = args.context_length
    device_num = args.device_num
    core_num = args.core_num
    batch = args.batch
    j = args.j
    flash_attention = args.flash_attention
    strip = args.strip

    model_name_ori = model_name

    # Get the information of supported models
    with open("./supported_models.json", "r", encoding="utf-8") as md_file:
        model_info = json.load(md_file)
    try:
        if model_name not in model_info:
            logger.error(f"Unsupport model {model_name}.")
            exit(2)
        if model_size not in model_info[model_name]:
            logger.error(f"Unsupport model size {model_name} {model_size}.")
            exit(2)
        if target not in model_info[model_name][model_size]["support_backends"]:
            logger.error(f"{model_name} {model_size} does not support {target}.")
            exit(2)
        model_dir = model_info[model_name][model_size]["path"]  # releative path
        raw_model_path = model_info[model_name][model_size]["raw"]  # releative path
    except Exception as e:
        logger.error(
            f"Unsupported model {model_name} {model_size}, error msg: {str(e)}"
        )
        exit(2)

    # Create a result folder for the current container
    if args.task_id:
        container_name = f"compiler_{target}_{version}_{task_id}"
        logger.info(f"start container with task_id:{task_id} in name:{container_name} ")
    else:
        container_name = f"compiler_{target}_{version}_{ts_str}"
    host_result_dir += f"/{container_name}"
    os.makedirs(host_result_dir, exist_ok=True)

    host_quant_model = (
        f"{host_result_dir}/quant_results"
        if "http" in quant_model_path
        else quant_model_path
    )
    logger.info(f"##hm host_quant_model is:{host_quant_model}")
    if not quant_model_path:
        quant_flag = True
    else:
        quant_flag = False
        os.makedirs(host_quant_model, exist_ok=True)

    ###### Docker Executor ######
    # The folder that stores the original model structure and weights
    host_model_zoo = "/data/gexinyu_workspace/modelzoo"
    # Construct docker image name
    system = "ubuntu20.04" if target == "xh1" else "ubuntu24.04"
    image_name = f"harbor.houmo.ai/toolchain/release:Dadao-{target}-v{version}-{system}-x86.64.latest"
    # Set container configs
    container_home = "/hmdd"
    container_result_dir = f"{container_home}/results"
    container_log_file = container_home + "/logs/" + host_log_file.rsplit("/", 1)[-1]
    # Construct the commands to be executed in the container
    commands = ["echo 'Hi LLM Compiler!'"]
    if quant_flag:
        # Quantization command
        container_quant_res = f"{container_result_dir}/quant_results"
        quant_cmd = f"python3 execute_quantization.py -t {target} -m {model_dir} -n {model_name} -raw {raw_model_path} -b {batch} -pl {prefill_len} -cl {context_len} -r {container_quant_res} -log {container_log_file}"
        commands.append(
            f"cd {container_home}/imodelzoo/service/llm_compiler && {quant_cmd}"
        )
        quant_model = f"{container_quant_res}/hmquant"
    else:
        quant_model = f"{container_home}/quant_model"
        check_cmd = f"python3 check_quant_folder.py -n {model_name} -qm {quant_model} -path {quant_model_path}"
        commands.append(
            f"cd {container_home}/imodelzoo/service/llm_compiler && {check_cmd}"
        )

    if args.forced_compile or not quant_flag:
        # Compilation command
        container_compile_res = f"{container_result_dir}/compile_results"
        compile_cmd = f"python3 execute_compilation.py -n {model_name} -m {model_dir} -qm {quant_model} "
        if context_len >= 128:
            compile_cmd += f"-cl {context_len} "
        if device_num >= 0:
            compile_cmd += f"-dn {device_num} "
        if batch > 0:
            compile_cmd += f"-b {batch} "
        if core_num > 0:
            compile_cmd += f"-cn {core_num} "
        if flash_attention >= 0:
            compile_cmd += f"--flash_attention {flash_attention} "
        compile_cmd += f"-j {j} --strip {strip} -r {container_compile_res} -log {container_log_file}"
        commands.append(
            f"cd {container_home}/imodelzoo/service/llm_compiler && {compile_cmd}"
        )

    # Create a docker executor
    docker_exec = DockerExecutor(
        image=image_name,
        container_name=container_name,
        host_log_path=host_log_file,
        container_workdir=container_home,
        keep_container=False,
    )
    docker_flag = True
    try:
        docker_exec.pull_image()
        # Map the current directory of the host to the container
        volumes = {
            # Map imodelzoo folder
            os.path.abspath(f"{script_dir}/../../"): {
                "bind": f"{container_home}/imodelzoo",
                "mode": "rw",
            },
            # Map original models folder
            host_model_zoo: {
                "bind": "/modelzoo",
                "mode": "rw",
            },
            # Map results folder
            os.path.abspath(host_result_dir): {
                "bind": container_result_dir,
                "mode": "rw",
            },
            # Map logs folder
            os.path.abspath(log_dir): {
                "bind": f"{container_home}/logs",
                "mode": "rw",
            },
        }
        if quant_flag:
            gpu_env = {
                "NVIDIA_VISIBLE_DEVICES": "all",
                "NVIDIA_DRIVER_CAPABILITIES": "compute,utility",
            }
            docker_exec.start_container(
                volumes=volumes, environment=gpu_env, task_id=args.task_id
            )
        else:
            volumes[os.path.abspath(host_quant_model)] = {
                "bind": f"{container_home}/quant_model",
                "mode": "rw",
            }
            docker_exec.start_container(volumes=volumes, task_id=args.task_id)
        cmds_res = docker_exec.execute_commands(commands, stop_on_error=True)
        for res in cmds_res:
            if res.get("exit_code", -1) != 0:
                logger.info("## hm docker_exec commands error occured")
                docker_flag = False
                break
    except Exception as e:
        docker_flag = False
        logger.error(f"Error occurred: {str(e)}")
    finally:
        docker_exec.stop_and_remove_container()

    jfrog_path_quant = (
        args.quant_model_path if "http" in args.quant_model_path else None
    )
    md5sum_quant = None
    compiled_file_name = None
    context_str = (
        str(int(context_len / 1024)) + "k"
        if context_len >= 1024
        else f"{(context_len/1024)}k"
    )
    chip_str = f"{device_num}chips" if device_num > 1 else "1chip"
    core_str = f"{core_num}cores" if core_num > 1 else f"{core_num}core"

    if docker_flag and args.upload is True:
        version_str = f"{target}-v{version}" if args.release is True else ""
        if version_str:
            model_name = "deepseek" if "deepseek" in model_name else model_name
        current_dt = datetime.now()
        current_ts = (
            current_dt.strftime("%Y%m%d_%H%M%S") if not version_str else f"v{version}"
        )
        today = current_dt.strftime("%Y%m%d")
        if quant_flag:
            # Publish quantized model (will upload to Jfrog)
            host_quant_dir = host_result_dir + "/quant_results/hmquant"
            quant_file_name = f"hmquant_{target}_{model_name}_{model_size}_"
            if prefill_len > 0:
                quant_file_name += f"{prefill_len}_"
            if context_len > 0:
                quant_file_name += f"{context_str}_"
            quant_file_name += f"{current_ts}.zip"

            md5sum_quant, jfrog_path_quant = _publish_model(
                today,
                quant_file_name,
                host_quant_dir,
                host_result_dir,
                model_name,
                host_log_file,
                version_str,
            )
            if jfrog_path_quant is None or md5sum_quant is None:
                logger.error(f"Failed to publish quant model {host_quant_dir}.")
                exit(44)
            else:
                logger.info(
                    f"#hm upload to jfrog success with quantpath:{jfrog_path_quant}"
                )
        elif jfrog_path_quant:
            compressed_quant_file = (
                f"{host_result_dir}/quant_results/"
                + quant_model_path.rsplit("/", 1)[-1]
            )
            md5sum_quant = _get_md5sum(compressed_quant_file)

        # Upload the compiled files only when disabling quant.
        if args.forced_compile or not quant_flag:
            # publish compiled model (will upload to Jfrog)
            host_compile_dir = host_result_dir + "/compile_results"
            compiled_file_name = f"hmm_{target}_{model_name}_{model_size}_"
            if prefill_len > 0:
                compiled_file_name += f"{prefill_len}_"
            if context_len > 0:
                compiled_file_name += f"{context_str}_"
            if batch > 0:
                compiled_file_name += f"b{batch}_"
            compiled_file_name += f"{chip_str}_{core_str}_{current_ts}.zip"
            md5sum_compile, jfrog_path_compile = _publish_model(
                today,
                compiled_file_name,
                host_compile_dir,
                host_result_dir,
                model_name,
                host_log_file,
                version_str,
                [".hmm", ".hmms", ".pt"],
            )
            if jfrog_path_compile is None or md5sum_compile is None:
                logger.error(f"Failed to publish compiled model {host_compile_dir}.")
                exit(4)
            else:
                logger.info(
                    f"#hm upload to jfrog success with path:{jfrog_path_compile}"
                )

            # Update published model table: published_models.csv
            publish_dt = current_dt.strftime("%Y%m%d %H:%M:%S")
            model_id = f"{os.getpid()}-{current_ts}"
            version_str = f"v{version}"
            new_model = {
                "model_id": model_id,
                "model_name": model_name,
                "model_size": model_size,
                "prefill_length": prefill_len,
                "context_length": context_len,
                "version": version_str,
                "target": target,
                "device_num": device_num,
                "core_num": core_num,
                "publish_time": publish_dt,
                "model_md5sum": md5sum_compile,
                "quant_model_md5sum": md5sum_quant,
                "model_path": jfrog_path_compile,
                "quant_model_path": jfrog_path_quant,
            }
            ret = _update_model_table(new_model)
            if ret is False:
                logger.info("## hm enter here5")
                exit(5)

    if args.perf_config and target == "xh2" and device_num <= 2:
        perf_mode = model_info[model_name_ori][model_size]["perf"]

        if compiled_file_name is None:
            compiled_file_name = f"{target}_{model_name}_{model_size}_"
            if prefill_len > 0:
                compiled_file_name += f"{prefill_len}_"
            if context_len > 0:
                compiled_file_name += f"{context_str}_"
            if batch > 0:
                compiled_file_name += f"b{batch}_"
            compiled_file_name += f"{chip_str}_{core_str}_v{version}"

        compile_results_dir = f"{host_result_dir}/compile_results"

        if perf_mode in ["llm_perf"]:
            new_stream = {
                "ModelName": compiled_file_name,
                "prefill": f"{compile_results_dir}/{model_name}_prefill.hmm",
                "decode": f"{compile_results_dir}/{model_name}_decode.hmm",
                "embedding": f"{compile_results_dir}/hmquant/quant_embedding.bin",
                "input": 256,
                "stop": 2048,
                "ndevices": device_num if device_num > 1 else 1,
                "loop": 2,
                "batch": batch,
            }
            if context_len < (2048 + 256) and context_len >= (1024 + 256):
                new_stream["stop"] = 1024
            elif context_len > 0 and context_len < (1024 + 256):
                new_stream["input"] = int(context_len * 0.2)
                new_stream["stop"] = context_len - new_stream["input"]
            if "-vl" in model_name_ori:
                new_stream["visual"] = f"{compile_results_dir}/{model_name}_visual.hmm"
            if device_num > 1:
                new_stream["prefill"] = new_stream["prefill"] + "s"
                new_stream["decode"] = new_stream["decode"] + "s"
                if "visual" in new_stream:
                    new_stream["visual"] = new_stream["visual"] + "s"

            cfg_path = args.perf_config

        elif perf_mode in ["tcim_perf"]:
            hmm_list = glob.glob(f"{compile_results_dir}/*.hmm")
            new_stream = {
                "ModelName": compiled_file_name,
                "hmm_list": hmm_list,
                "samples": 100,
                "devices": device_num if device_num > 1 else 1,
                "batch": batch,
                "name": model_name_ori,
                "loops": 1,
                "warm_up": 1,
            }
            # _tcim.json
            cfg_path = args.perf_config.replace(".json", "_tcim.json")

        elif perf_mode in ["demo"]:
            new_stream = {
                "ModelName": compiled_file_name,
                "model_dir": model_dir,
                "hmm_dir": compile_results_dir,
                "ndevices": device_num if device_num > 1 else 1,
            }
            # _demo.json
            cfg_path = args.perf_config.replace(".json", "_demo.json")

        if os.path.exists(cfg_path):
            try:
                with open(cfg_path, "r", encoding="utf-8") as f:
                    cfg_data = json.load(f)
            except json.JSONDecodeError:
                logger.error(
                    f"{cfg_path} is not a valid JSON file. A new file will be created."
                )
                cfg_data = {"Streams": []}
        else:
            logger.error(f"{cfg_path} does not exist. A new file will be created.")
            cfg_data = {"Streams": []}

        if "Streams" not in cfg_data or not isinstance(cfg_data["Streams"], list):
            logger.warning("JSON structure is abnormal. Reset Streams to list.")
            cfg_data["Streams"] = []

        cfg_data["Streams"].append(new_stream)

        with open(cfg_path, "w", encoding="utf-8") as f:
            json.dump(cfg_data, f, indent=2, ensure_ascii=False, sort_keys=False)
        logger.info(
            f"Successful addition of configuration. The current total number of Perf models:{len(cfg_data['Streams'])}"
        )

    del_suffixes = args.delete_filetypes
    delete_files(host_result_dir, [".zip"])
    if len(del_suffixes) > 0:
        logger.info(f"Start to clear result files {del_suffixes}")
        delete_files(host_result_dir, del_suffixes)
        quant_work_dir = f"{script_dir}/../../{model_dir}/work_dirs"
        if os.path.exists(quant_work_dir):
            delete_files(quant_work_dir, del_suffixes)

    if not docker_flag:
        logger.info("### something error in docker container")
        exit(-1)
