
default_model_name: "deepseek"
default_model_size: "8b"

model_configs:
  deepseek:
    "8b":
      modelscope_repo: ["deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"]
      model_name: "deepseek"
      model_size: "8b"
      ncore: 2
      quant_type: "w4a8h0_ssfp"
      context_length: "32k"
      ndevice: 1
      batch: 1
      prefill_length: 256