default_model_name: "bge"
default_model_size: "0.5b"

model_configs:
  bge:
    "0.5b":
      modelscope_repo: ["BAAI/bge-reranker-v2-m3", "BAAI/bge-m3"]
      model_name: "bge"
      model_size: "0.5b"
      embedder_name: "bge-m3"
      reranker_name: "bge-reranker-v2-m3"
      ncore: 2
      quant_type: "w8a8_sefp"
      context_length: "0.5k"
      ndevice: 1
      batch: 10