#!/usr/bin/env python3
# Copyright (c) 2026 HOUMO AI
#
# File: build.py
# Description:
#   Compile Fun-Audio-Chat HMONNX graphs into HMM artifacts.
#   Build the FunAudioChat HMM artifacts from the release HMONNX layout.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import argparse
import multiprocessing
import os
from pathlib import Path

from hmatc.exec.xh2_exec import Xh2Exec
from hmatc.utils.utils import (
    find_hmonnx_file,
    first_not_none,
    get_model_configs,
    get_platform,
)

HOUMO_TARGET = os.getenv("HOUMO_TARGET")
assert HOUMO_TARGET == "xh2", f"Unsupported HOUMO_TARGET: {HOUMO_TARGET}"
HOUMO_CORE_NUM = int(os.getenv("HOUMO_CORE_NUM", 2))
DEFAULT_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.yaml")

BUILD_TARGETS = (
    ("audio_tower", False, 0, False),
    ("audio_encoder", False, 0, False),
    ("prefill", True, 2, True),
    ("decode", False, 2, True),
    ("audio_decoder_prefill", True, 2, False),
    ("audio_decoder_decode", False, 2, False),
)


def _find_graph(model_dir: Path, component_dir_name: str) -> Path:
    component_dir = model_dir / component_dir_name
    if not component_dir.is_dir():
        raise FileNotFoundError(f"Component directory not found: {component_dir}")
    try:
        return Path(find_hmonnx_file(str(component_dir)))
    except (FileNotFoundError, RuntimeError) as exc:
        raise FileNotFoundError(f"HMONNX file not found under: {component_dir}") from exc


def _build_one(
    graph_path: Path,
    hmm_name: str,
    output_dir: Path,
    args: argparse.Namespace,
    *,
    prefill: bool,
    flash_attn: int,
    llm_opt: bool,
) -> None:
    output_suffix = "hmms" if args.ndevice > 1 and (prefill or "decode" in hmm_name) else "hmm"
    output_path = output_dir / f"{hmm_name}.{output_suffix}"
    print(
        f"\n[build] HMONNX -> HMM\n" f"        source: {graph_path}\n" f"        target: {output_path}\n",
        flush=True,
    )

    kwargs = dict(
        hmonnx=find_hmonnx_file(str(graph_path.parent), pattern=graph_path.name),
        hmm_name=hmm_name,
        output=str(output_dir),
        ncore=args.ncore,
        parallel_jobs=args.jobs,
        llm_opt=llm_opt,
        flash_attn=flash_attn,
        enable_xh2_stable_output=args.stable_output,
        ndevice=args.ndevice,
        enable_common_subgraph=args.enable_common_subgraph if prefill else False,
    )

    Xh2Exec.build_from_hmonnx(**kwargs)
    print(f"[build] completed: {graph_path.name} -> {output_path}\n", flush=True)


def build(model_dir: Path, output_dir: Path, args: argparse.Namespace) -> None:
    if get_platform() != "x86_64":
        raise RuntimeError("FunAudioChat HMM compilation requires x86_64")

    output_dir.mkdir(parents=True, exist_ok=True)
    model_prefix = f"{args.model_name}-{args.model_size}"
    for component_dir_name, prefill, flash_attn, llm_opt in BUILD_TARGETS:
        _build_one(
            _find_graph(model_dir, component_dir_name),
            f"{model_prefix}_{component_dir_name}",
            output_dir,
            args,
            prefill=prefill,
            flash_attn=flash_attn,
            llm_opt=llm_opt,
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Build FunAudioChat HMM artifacts from HMONNX files.")
    parser.add_argument("--config", dest="config_path", default=DEFAULT_CONFIG_PATH, help="path to config.yaml")
    parser.add_argument(
        "--model_dir",
        default=os.path.join("output", HOUMO_TARGET, "hmquant"),
        help="release hmquant directory generated by ptq.py",
    )
    parser.add_argument("--output_dir", default=os.path.join("output", HOUMO_TARGET))
    parser.add_argument("--model_name", default=None, help="model name")
    parser.add_argument("--model_size", default=None, help="model size")
    parser.add_argument("--batch", type=int, default=None)
    parser.add_argument("--ndevice", type=int, default=None)
    parser.add_argument("--ncore", type=int, default=None)
    parser.add_argument("--jobs", "-j", type=int, default=multiprocessing.cpu_count())
    parser.add_argument("--stable_output", action="store_true")
    parser.add_argument("--enable_common_subgraph", action="store_true")
    args = parser.parse_args()

    default_model_size, default_model_name, model_configs = get_model_configs(args.config_path)
    args.model_name = first_not_none(args.model_name, default_model_name)
    args.model_size = first_not_none(args.model_size, default_model_size)
    model_config = model_configs.get(args.model_name, {}).get(args.model_size, {})
    if not model_config:
        raise ValueError(f"Unsupported model configuration: {args.model_name}-{args.model_size}")
    args.batch = first_not_none(args.batch, model_config.get("batch", 1))
    args.ndevice = first_not_none(args.ndevice, model_config.get("ndevice", 1))
    args.ncore = first_not_none(args.ncore, model_config.get("ncore", HOUMO_CORE_NUM))

    build(
        Path(args.model_dir).expanduser().resolve(),
        Path(args.output_dir).expanduser().resolve(),
        args,
    )


if __name__ == "__main__":
    main()
