model: {
  framework: onnx,
  name: custom_multi_input,
  save_dir: ./output,
  weight: ./custom_multi_input.onnx,
  inputs: [
    {
      name: x,
      shape: [1, 4, 4],
      layout: ND,
      format: Float32Feature,
      dtype: float32,
    },
    {
      name: y,
      shape: [1, 4, 4],
      layout: ND,
      format: Float32Feature,
      dtype: float32,
    }
  ],
}

quant: {
  ptq_cfg_path: ,
  calib_dir: data,
  calib_num: 20,
  debug_level: 1,
  precision: int8,
  calib_method: minmax,
  data_path: data/0.npz,
}

build: {
  ncore: 1,
  opt_level: 2,
}

test: {
  data_path: data/99.npz,
}

perf: {
  test_num: 1000,
}

