default_model_name: "minicpm-v-4.6"
default_model_size: "1.3b"

model_configs:
  minicpm-v-4.6:
    "1.3b":
      modelscope_repo: ["OpenBMB/MiniCPM-V-4.6"]
      model_name: "minicpm-v-4.6"
      model_size: "1.3b"
      ncore: 2
      quant_type: "w8a8h1_sefp"
      context_length: "256k"
      ndevice: 1
      batch: 1
      prefill_length: 256
      workflow_config: "workflows/xh2a/llm_models/minicpm_v_4_6/0_8b/minicpm_v_4_6_xh2a_w8a8.yaml"
