default_model_name: "minicpmo"
default_model_size: "7b"

model_configs:
  minicpmo:
    "7b":
      modelscope_repo: ["OpenBMB/MiniCPM-o-2_6"]
      model_name: "minicpmo"
      model_size: "7b"
      ncore: 2
      ndevice: 1
      context_length: "4k"
      prefill_length: 256
      batch: 1
      quant_type: "w8a8h0_sefp"
