model:
  name: yolov5m-face
  save_dir: output
  model_path: yolov5m-face.onnx
  inputs:
    input:
      shape: [1, 3, 640, 640] # NCHW
      data_format: RGB
      mean: [0.0, 0.0, 0.0]
      std: [255.0, 255.0, 255.0]
      resize_type: 1
      padding_mode: 1
      padding_values: [114, 114, 114]
      resizer:
        toYUV_format: YUV444SP
  model_impl_module: model_impl
  model_impl_cls: YoloV5MFace

quant:
  calib_data: widerface/WIDER_val/images/0--Parade
  calib_num: 50
  config:
    mix_attn_outs:
      ["/model.23/Reshape", "/model.23/Reshape_2", "/model.23/Reshape_4"]

build:
  ncore: 1
  opt_level: 2

demo:
  data_dir: widerface/WIDER_val/images/8--Election_Campain
  num: 0

eval:
  data_dir: widerface
  num: 0
  dataset_module: dataset
  dataset_cls: Dataset
