default_model_name: "gpt-oss"
default_model_size: "20b"

model_configs:
  gpt-oss:
    "20b":
      modelscope_repo: ["openai-mirror/gpt-oss-20b"]
      model_name: "gpt-oss"
      model_size: "20b"
      ncore: 2
      context_length: "256k"
      ndevice: 1
      batch: 1
      prefill_length: 256
      cpp_backend: "v2"
    "120b":
      modelscope_repo: ["openai-mirror/gpt-oss-120b"]
      model_name: "gpt-oss"
      model_size: "120b"
      ncore: 2
      context_length: "128k"
      ndevice: 2
      batch: 1
      prefill_length: 256
      cpp_backend: "v1"
