###### modelzoo ######
# args: all, quant, compile, demo, compare, eval, perf
backbone_resnet50:
  include:
    - models/backbone/resnet50
  exclude:
    - models/backbone/resnet50/README.MD
  example_case:
    - backbone_resnet50_test:
        test_type: models_tests
        script: resnet50
        args: all
  test:
    - backbone_resnet50_test
backbone_efficientnet:
  include:
    - models/backbone/efficientnet
  exclude:
    - models/backbone/efficientnet/README.MD
  example_case:
    - backbone_efficientnet_test:
        test_type: models_tests
        script: efficientnet
        args: all
  test:
    - backbone_efficientnet_test
backbone_mobilenetv2:
  include:
    - models/backbone/mobilenetv2
  exclude:
    - models/backbone/mobilenetv2/README.MD
  example_case:
    - backbone_mobilenetv2_test:
        test_type: models_tests
        script: mobilenetv2
        args: all
  test:
    - backbone_mobilenetv2_test
backbone_ViT-B-16:
  include:
    - models/backbone/ViT-B-16
  exclude:
    - models/backbone/ViT-B-16/README.MD
  example_case:
    - backbone_ViT-B-16_test:
        test_type: models_tests
        script: ViT-B-16
        args: all
  test:
    - backbone_ViT-B-16_test
# autodrive_yolop:
#   include:
#     - models/autodrive/yolop
#   exclude:
#     - models/autodrive/yolop/README.MD
#   example_case:
#     - autodrive_yolop_test:
#         test_type: models_tests
#         script: yolop
#         args: all
#   test:
#     - autodrive_yolop_test
detection_yolov3:
  include:
    - models/detection/yolov3
  exclude:
    - models/detection/yolov3/README.MD
  example_case:
    - detection_yolov3_test:
        test_type: models_tests
        script: yolov3
        args: all
  test:
    - detection_yolov3_test
detection_yolov5s:
  include:
    - models/detection/yolov5s
  exclude:
    - models/detection/yolov5s/README.MD
  example_case:
    - detection_yolov5s_test:
        test_type: models_tests
        script: yolov5s
        args: all
  test:
    - detection_yolov5s_test
detection_yolov5s_feature:
  include:
    - models/detection/yolov5s_feature
  exclude:
    - models/detection/yolov5s_feature/README.MD
  example_case:
    - detection_yolov5s_feature_test:
        test_type: models_tests
        script: yolov5s_feature
        args: all
  test:
    - detection_yolov5s_feature_test
detection_yolov8m:
  include:
    - models/detection/yolov8m
  exclude:
    - models/detection/yolov8m/README.MD
  example_case:
    - detection_yolov8m_test:
        test_type: models_tests
        script: yolov8m
        args: all
  test:
    - detection_yolov8m_test
multi_input_custom_random_model:
  include:
    - models/multi_input_custom_random_model
  exclude: null
  example_case:
    - multi_input_custom_random_model_test:
        script: ../models/multi_input_custom_random_model/test.sh
  test:
    - multi_input_custom_random_model_test
detection_yolo12m:
  include:
    - models/detection/yolo12m
  exclude:
    - models/detection/yolo12m/README.MD
  example_case:
    - detection_yolo12m_test:
        test_type: models_tests
        script: yolo12m
        args: all
  test:
    - detection_yolo12m_test
estimation_yolov8m_pose:
  include:
    - models/estimation/yolov8m-pose
  exclude:
    - models/estimation/yolov8m-pose/README.MD
  example_case:
    - estimation_yolov8m_pose_test:
        test_type: models_tests
        script: yolov8m_pose
        args: all
  test:
    - estimation_yolov8m_pose_test
segmentation_yolov8m_seg:
  include:
    - models/segmentation/yolov8m-seg
  exclude:
    - models/segmentation/yolov8m-seg/README.MD
  example_case:
    - segmentation_yolov8m_seg_test:
        test_type: models_tests
        script: yolov8m_seg
        args: all
  test:
    - segmentation_yolov8m_seg_test
llm_qwen3:
  include:
    - models/llm/qwen3
  exclude:
    - models/llm/qwen3/README.MD
  example_case:
    - llm_qwen3_test:
        test_type: models_tests
        script: qwen3
        args: all
  test:
    - llm_qwen3_test
# llm_qwen2.5:
#   include:
#     - models/llm/qwen2.5
#   exclude:
#     - models/llm/qwen2.5/README.MD
#   example_case:
#     - llm_qwen2.5_test:
#         test_type: models_tests
#         script: qwen2dot5
#         args: all
#   test:
#     - llm_qwen2.5_test
# llm_qwen3_14b:
#   include:
#     - models/llm/qwen3-14b
#   exclude:
#     - models/llm/qwen3-14b/README.MD
#   example_case:
#     - llm_qwen3_14b_test:
#         test_type: models_tests
#         script: qwen3_14b
#         args: all
#   test:
#     - llm_qwen3_14b_test
# llm_deepseek_r1_qwen3_8b:
#   include:
#     - models/llm/deepseek-r1-qwen3-8b
#   exclude:
#     - models/llm/deepseek-r1-qwen3-8b/README.MD
#   example_case:
#     - llm_deepseek_r1_qwen3_8b_test:
#         test_type: models_tests
#         script: deepseek_r1_qwen3_8b
#         args: all
#   test:
#     - llm_deepseek_r1_qwen3_8b_test
# llm_deepseek:
#   include:
#     - models/llm/deepseek
#   exclude:
#     - models/llm/deepseek/README.MD
#   example_case:
#     - llm_deepseek_test:
#         test_type: models_tests
#         script: deepseek
#         args: all
#   test:
#     - llm_deepseek_test
asr_wenet:
  include:
    - models/asr/wenet
  exclude:
    - models/asr/wenet/README.MD
  example_case:
    - asr_wenet_test:
        test_type: models_tests
        script: wenet
        args: all
  test:
    - asr_wenet_test
utils:
  include:
    - utils
    - release.cmake
    # - env.sh
  exclude: null
  example_case: null
  test:
    - backbone_resnet50_test
    - detection_yolov5s_test
    - autodrive_yolop_test

###### hmatc ######
hmatc:
  include:
    - hmatc
  exclude:
    - hmatc/README.MD
    - hmatc/.clang-format
  example_case: null
  test:
    # test models
    - backbone_resnet50_test
    - detection_yolov5s_test

tools_computing_perf:
  include:
    - apis/tools/computing_perf
  exclude:
    - apis/tools/computing_perf/README.MD
  example_case:
    - tools_computing_perf_test:
        script: ../apis/tools/computing_perf/run.sh
  test:
    - tools_computing_perf_test

tools_bandwidth_perf:
  include:
    - apis/tools/bandwidth_perf
  exclude:
    - apis/tools/bandwidth_perf/README.MD
  example_case:
    - tools_bandwidth_perf_test:
        script: ../apis/tools/bandwidth_perf/run.sh
  test:
    - tools_bandwidth_perf_test

###### apis ######
inferences_resnet50:
  include:
    - apis/inferences/resnet50
  exclude:
    - apis/inferences/resnet50/README.MD
  example_case:
    - inferences_resnet50_test:
        test_type: apis_tests
        script: resnet50 and inference
        args: all
  test:
    - inferences_resnet50_test
inferences_yolov5s:
  include:
    - apis/inferences/yolov5s
  exclude:
    - apis/inferences/yolov5s/README.MD
  example_case:
    - inferences_yolov5s_test:
        test_type: apis_tests
        script: yolov5s and inference
        args: all
  test:
    - inferences_yolov5s_test
inferences_yolov5s_dynamic:
  include:
    - apis/inferences/yolov5s_dynamic
  exclude:
    - apis/inferences/yolov5s_dynamic/README.MD
  example_case:
    - inferences_yolov5s_dynamic_test:
        script: ../apis/inferences/yolov5s_dynamic/run.sh
  test:
    - inferences_yolov5s_dynamic_test
inferences_resnet50_multistreams:
  include:
    - apis/inferences/resnet50_multistreams
  exclude:
    - apis/inferences/resnet50_multistreams/README.MD
  example_case:
    - inferences_resnet50_multistreams_test:
        test_type: apis_tests
        script: resnet50 and multistreams
        args: all
  test:
    - inferences_resnet50_multistreams_test
inferences_resnet50_pipeline:
  include:
    - apis/inferences/resnet50_pipeline
  exclude:
    - apis/inferences/resnet50_pipeline/README.MD
  example_case:
    - inferences_resnet50_pipeline_test:
        test_type: apis_tests
        script: resnet50 and pipeline
        args: all
  test:
    - inferences_resnet50_pipeline_test
inferences_yolov5s_resnet50_multibatch:
  include:
    - apis/inferences/yolov5s_resnet50_multibatch
  exclude:
    - apis/inferences/yolov5s_resnet50_multibatch/README.MD
  example_case:
    - inferences_yolov5s_resnet50_multibatch_test:
        test_type: apis_tests
        script: yolov5s and resnet50 and multibatch
        args: all
  test:
    - inferences_yolov5s_resnet50_multibatch_test
scenes_video_detect:
  include:
    - apis/scenes/video_detect
  exclude:
    - apis/scenes/video_detect/README.MD
  example_case:
    - scenes_video_detect_test:
        test_type: apis_tests
        script: video_detect
        args: all
  test:
    - scenes_video_detect_test
scenes_buffer_pool:
  include:
    - apis/scenes/buffer_pool
  exclude:
    - apis/scenes/buffer_pool/README.MD
  example_case:
    - scenes_buffer_pool_test:
        script: ../apis/scenes/buffer_pool/run.sh
  test:
    - scenes_buffer_pool_test
apis_common:
  include:
    - apis/common
  exclude: null
  example_case: null
  test:
    - inferences_resnet50_test
    - inferences_yolov5s_test
    - inferences_resnet50_multistreams_test
    - inferences_resnet50_pipeline_test
    - inferences_yolov5s_resnet50_multibatch_test
    - scenes_video_detect_test

###### tools ######
tools_tcim_perf:
  include:
    - tools/tcim_perf
  exclude:
    - tools/tcim_perf/README.MD
  example_case:
    - tcim_perf_test:
        script: ../tools/tcim_perf/build.sh
  test:
    # - tcim_perf_test

###### tests ######
models_tests:
  include:
    - tests/models_tests
  exclude:
    - tests/models_tests/README.md
    - tests/models_tests/__init__.py
  example_case: null
  test:
    - asr_wenet_test
    - backbone_resnet50_test
    - detection_yolov5s_test

apis_tests:
  include:
    - tests/apis_tests
  exclude:
    - tests/apis_tests/__init__.py
  example_case: null
  test:
    - inferences_resnet50_test
    - inferences_yolov5s_test
    - inferences_resnet50_multistreams_test
    - inferences_resnet50_pipeline_test
    - inferences_yolov5s_resnet50_multibatch_test
    - scenes_video_detect_test

###### all ######
all:
  include:
    - run_all.py
  exclude: null
  example_case: null
  test:
    ### modelzoo ###
    # - backbone_resnet50_test
    # - backbone_efficientnet_test
    # - backbone_mobilenetv2_test
    # - autodrive_yolop_test
    # - detection_yolov3_test
    # - detection_yolov5s_test
    # - detection_yolov8m_test
    # - asr_wenet_test
    ### apis ###
    # - inferences_resnet50_test
    # - inferences_yolov5s_test
    # - inferences_resnet50_multistreams_test
    # - inferences_resnet50_pipeline_test
    # - inferences_yolov5s_resnet50_multibatch_test
    # - scenes_video_detect_test
    ### hmatc ###
