# modelzoo
backbone_resnet50:
  include:
    - models/backbone/resnet50
  exclude:
    - models/backbone/resnet50/README.MD
  example_case:
    - backbone_resnet50_perf:
        script: models/backbone/resnet50/perf.sh
    - backbone_resnet50_eval:
        script: models/backbone/resnet50/eval.sh
    - backbone_resnet50_test:
        script: models/backbone/resnet50/test.sh
  test:
    - backbone_resnet50_eval
    - backbone_resnet50_perf
    - backbone_resnet50_test
backbone_efficientnet:
  include:
    - models/backbone/efficientnet
  exclude:
    - models/backbone/efficientnet/README.MD
  example_case:
    - backbone_efficientnet_eval:
        script: models/backbone/efficientnet/eval.sh
    - backbone_efficientnet_perf:
        script: models/backbone/efficientnet/perf.sh
    - backbone_efficientnet_test:
        script: models/backbone/efficientnet/test.sh
  test:
    - backbone_efficientnet_eval
    - backbone_efficientnet_perf
    - backbone_efficientnet_test
backbone_mobilenetv2:
  include:
    - models/backbone/mobilenetv2
  exclude:
    - models/backbone/mobilenetv2/README.MD
  example_case:
    - backbone_mobilenetv2_eval:
        script: models/backbone/mobilenetv2/eval.sh
    - backbone_mobilenetv2_perf:
        script: models/backbone/mobilenetv2/perf.sh
    - backbone_mobilenetv2_test:
        script: models/backbone/mobilenetv2/test.sh
  test:
    - backbone_mobilenetv2_eval
    - backbone_mobilenetv2_perf
    - backbone_mobilenetv2_test
backbone_vit:
  include:
    - models/backbone/vit
  exclude: null
  example_case:
    - backbone_vit_perf:
        script: models/backbone/vit/perf.sh
  test:
    # - backbone_vit_perf
autodrive_yolop:
  include:
    - models/autodrive/yolop
  exclude:
    - models/autodrive/yolop/README.MD
  example_case:
    - autodrive_yolop_perf:
        script: models/autodrive/yolop/perf.sh
    - autodrive_yolop_test:
        script: models/autodrive/yolop/test.sh
  test:
    - autodrive_yolop_perf
    - autodrive_yolop_test
detection_yolov3:
  include:
    - models/detection/yolov3
  exclude:
    - models/detection/yolov3/README.MD
  example_case:
    - detection_yolov3_eval:
        script: models/detection/yolov3/eval.sh
    - detection_yolov3_perf:
        script: models/detection/yolov3/perf.sh
    - detection_yolov3_test:
        script: models/detection/yolov3/test.sh
  test:
    - detection_yolov3_eval
    - detection_yolov3_perf
    - detection_yolov3_test
detection_yolov5s:
  include:
    - models/detection/yolov5s
  exclude:
    - models/detection/yolov5s/README.MD
  example_case:
    - detection_yolov5s_eval:
        script: models/detection/yolov5s/eval.sh
    - detection_yolov5s_perf:
        script: models/detection/yolov5s/perf.sh
    - detection_yolov5s_test:
        script: models/detection/yolov5s/test.sh
  test:
    - detection_yolov5s_eval
    - detection_yolov5s_perf
    - detection_yolov5s_test
detection_yolov8m:
  include:
    - models/detection/yolov8m
  exclude:
    - models/detection/yolov8m/README.MD
  example_case:
    - detection_yolov8m_eval:
        script: models/detection/yolov8m/eval.sh
    - detection_yolov8m_perf:
        script: models/detection/yolov8m/perf.sh
    - detection_yolov8m_test:
        script: models/detection/yolov8m/test.sh
  test:
    - detection_yolov8m_eval
    - detection_yolov8m_perf
    - detection_yolov8m_test
asr_wenet:
  include:
    - models/asr/wenet
  exclude:
    - models/asr/wenet/README.MD
  example_case:
    - asr_wenet_test:
        script: models/asr/wenet/test.sh
  test:
    - asr_wenet_test
tests_qwen_1block:
  include:
    - tests/qwen_1block
  exclude:
    - tests/qwen_1block/README.MD
  example_case:
    - qwen_1block_4core_test:
        script: tests/qwen_1block/test.sh --core 4
    - qwen_1block_2core_test:
        script: tests/qwen_1block/test.sh --core 2
    - qwen_1block_1core_test:
        script: tests/qwen_1block/test.sh --core 1
  test:
    # - qwen_1block_4core_test
    # - qwen_1block_2core_test
    # - qwen_1block_1core_test
tests_qwen2_2blocks:
  include:
    - tests/qwen2_2blocks
  exclude:
    - tests/qwen2_2blocks/README.MD
  example_case:
    - qwen2_2blocks_4core_test:
        script: tests/qwen2_2blocks/test.sh --core 4
    - qwen2_2blocks_2core_test:
        script: tests/qwen2_2blocks/test.sh --core 2
  test:
    # - qwen2_2blocks_4core_test
    # - qwen2_2blocks_2core_test
utils:
  include:
    - utils
    - release.cmake
    - env.sh
  exclude: null
  example_case: null
  test:
    - backbone_resnet50_perf
    - autodrive_yolop_perf
    - detection_yolov5s_perf
hmassist:
  include:
    - hmassist
  exclude:
    - hmassist/README.MD
  example_case: null
  test:
    - backbone_resnet50_perf
    - backbone_resnet50_eval
    - backbone_resnet50_test
    - detection_yolov5s_perf
    - detection_yolov5s_eval
    - detection_yolov5s_test

# examples
examples_common:
  include:
    - examples/common
  exclude: null
  example_case: null
  test:
    - inferences_resnet50_test
    - inferences_resnet50_multistreams_test
    - inferences_resnet50_pipeline_test
    - inferences_yolov5s_test
    # - scenes_video_detect_test
inferences_resnet50:
  include:
    - examples/inferences/resnet50
  exclude:
    - examples/inferences/resnet50/README.MD
  example_case:
    - inferences_resnet50_test:
        script: examples/inferences/resnet50/run.sh
  test:
    - inferences_resnet50_test
inferences_resnet50_multistreams:
  include:
    - examples/inferences/resnet50_multistreams
  exclude:
    - examples/inferences/resnet50_multistreams/README.MD
  example_case:
    - inferences_resnet50_multistreams_test:
        script: examples/inferences/resnet50_multistreams/run.sh
  test:
    - inferences_resnet50_multistreams_test
inferences_resnet50_pipeline:
  include:
    - examples/inferences/resnet50_pipeline
  exclude:
    - examples/inferences/resnet50_pipeline/README.MD
  example_case:
    - inferences_resnet50_pipeline_test:
        script: examples/inferences/resnet50_pipeline/run.sh
  test:
    - inferences_resnet50_pipeline_test
inferences_yolov5s:
  include:
    - examples/inferences/yolov5s
  exclude:
    - examples/inferences/yolov5s/README.MD
  example_case:
    - inferences_yolov5s_test:
        script: examples/inferences/yolov5s/run.sh
  test:
    - inferences_yolov5s_test
scenes_video_detect:
  include:
    - examples/scenes/video_detect
  exclude:
    - examples/scenes/video_detect/README.MD
  example_case:
    - scenes_video_detect_test:
        script: examples/scenes/video_detect/run.sh
  test:
    # - scenes_video_detect_test

all:
  include:
    - run_all.py
  exclude: null
  example_case: null
  test:
    # modelzoo
    - backbone_resnet50_perf
    - backbone_resnet50_eval
    - backbone_resnet50_test
    - backbone_efficientnet_eval
    - backbone_efficientnet_perf
    - backbone_efficientnet_test
    - backbone_mobilenetv2_eval
    - backbone_mobilenetv2_perf
    - backbone_mobilenetv2_test
    # - backbone_vit_perf
    - autodrive_yolop_perf
    - autodrive_yolop_test
    - detection_yolov3_eval
    - detection_yolov3_perf
    - detection_yolov3_test
    - detection_yolov5s_perf
    - detection_yolov5s_eval
    - detection_yolov5s_test
    - detection_yolov8m_perf
    - detection_yolov8m_eval
    - detection_yolov8m_test
    - asr_wenet_test
    # - qwen_1block_4core_test
    # - qwen_1block_2core_test
    # - qwen_1block_1core_test
    # - qwen2_2blocks_4core_test
    # - qwen2_2blocks_2core_test
    # examples
    - inferences_resnet50_test
    - inferences_resnet50_multistreams_test
    - inferences_resnet50_pipeline_test
    - inferences_yolov5s_test
    # - scenes_video_detect_test
