# Copyright (c) 2026 HOUMO AI
#
# File: build.py
# Description:
#   MiniCPM-V 4.5 model compilation tool.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import argparse
import multiprocessing
import os
from pathlib import Path

from hmatc.exec.xh2_exec import Xh2Exec
from hmatc.utils.utils import (
    find_hmonnx_file,
    first_not_none,
    get_model_configs,
    get_platform,
    parse_context_length,
)

HOUMO_TARGET = os.getenv("HOUMO_TARGET")
assert HOUMO_TARGET == "xh2", f"Unsupported HOUMO_TARGET: {HOUMO_TARGET}"

DEFAULT_CONFIG_PATH = Path(__file__).resolve().parent / "config.yaml"
HOUMO_CORE_NUM = int(os.getenv("HOUMO_CORE_NUM", 2))


def _validate_flash_attention(values: tuple[int, int]) -> tuple[int, int]:
    llm_value, vision_value = values
    if llm_value not in (0, 1, 2):
        raise ValueError("Prefill/decode FlashAttention only supports 0, 1, or 2, " f"got {llm_value}")
    if vision_value not in (0, 1):
        raise ValueError(f"Vision FlashAttention only supports 0 or 1, got {vision_value}")
    return llm_value, vision_value


def _resolve_model_dirs(model_dir: Path) -> tuple[Path, Path, list[Path]]:
    prefill_dir = model_dir / "prefill"
    decode_dirs = sorted(path for path in model_dir.glob("*decode*") if path.is_dir())
    vision_dirs = sorted(path for path in model_dir.glob("vision_*") if path.is_dir())

    if not prefill_dir.is_dir():
        raise FileNotFoundError(f"Prefill directory not found: {prefill_dir}")
    if len(decode_dirs) != 1:
        raise FileNotFoundError(f"Expected exactly one decode directory under {model_dir}, found {decode_dirs}")
    if not vision_dirs:
        raise FileNotFoundError(f"No vision_* directories found under: {model_dir}")
    return prefill_dir, decode_dirs[0], vision_dirs


def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compile MiniCPM-V 4.5 HMONNX models for Houmo XH2.")
    parser.add_argument("--config", dest="config_path", default=str(DEFAULT_CONFIG_PATH))
    parser.add_argument(
        "--model_dir",
        default=os.path.join("output", HOUMO_TARGET, "hmquant"),
        help="directory generated by ptq.py",
    )
    parser.add_argument("--model_name", default=None)
    parser.add_argument("--model_size", default=None)
    parser.add_argument("--batch", type=int, default=None)
    parser.add_argument("--ncore", type=int, default=None)
    parser.add_argument("--ndevice", type=int, default=None)
    parser.add_argument("--context_length", type=int, default=None)
    parser.add_argument("--prefill_length", type=int, default=None)
    parser.add_argument("--j", type=int, default=multiprocessing.cpu_count())
    parser.add_argument(
        "--output_dir",
        default=os.path.join("output", HOUMO_TARGET),
        help="directory for compiled HMM models",
    )
    parser.add_argument(
        "--flash_attention",
        nargs=2,
        type=int,
        default=(2, 1),
        metavar=("LLM", "VISION"),
        help="FlashAttention modes for prefill/decode and vision",
    )
    parser.add_argument("--enable_common_subgraph", action="store_true")
    parser.add_argument("--enable_xh2_stable_output", action="store_true")
    args = parser.parse_args()

    default_size, default_name, model_configs = get_model_configs(args.config_path)
    args.model_name = first_not_none(args.model_name, default_name)
    args.model_size = first_not_none(args.model_size, default_size)
    model_config = model_configs.get(args.model_name, {}).get(args.model_size)
    if model_config is None:
        raise ValueError(f"Unsupported model configuration: {args.model_name}-{args.model_size}")

    args.batch = first_not_none(args.batch, model_config.get("batch", 1))
    args.ncore = first_not_none(args.ncore, model_config.get("ncore", HOUMO_CORE_NUM))
    args.ndevice = first_not_none(args.ndevice, model_config.get("ndevice", 1))
    args.prefill_length = first_not_none(args.prefill_length, model_config.get("prefill_length", 256))
    if args.context_length is None:
        args.context_length = parse_context_length(model_config.get("context_length", "40k"))
    args.flash_attention = _validate_flash_attention(tuple(args.flash_attention))
    return args


def main() -> None:
    args = get_args()
    if get_platform() != "x86_64":
        raise RuntimeError("MiniCPM-V 4.5 compilation is only supported on x86_64")

    model_dir = Path(args.model_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    prefill_dir, decode_dir, vision_dirs = _resolve_model_dirs(model_dir)
    llm_flash_attention, vision_flash_attention = args.flash_attention
    model_prefix = f"{args.model_name}-{args.model_size}"

    for vision_dir in vision_dirs:
        profile = vision_dir.name.removeprefix("vision_")
        Xh2Exec.build_from_hmonnx(
            hmonnx=find_hmonnx_file(str(vision_dir)),
            hmm_name=f"{model_prefix}_visual_{profile}",
            output=str(output_dir),
            ncore=args.ncore,
            flash_attn=vision_flash_attention,
            parallel_jobs=args.j,
        )

    Xh2Exec.build_from_hmonnx(
        is_prefill=True,
        hmonnx=find_hmonnx_file(str(prefill_dir)),
        hmm_name=f"{model_prefix}_prefill",
        output=str(output_dir),
        flash_attn=llm_flash_attention,
        context_length=args.context_length,
        prefill_length=args.prefill_length,
        ndevice=args.ndevice,
        ncore=args.ncore,
        enable_common_subgraph=args.enable_common_subgraph,
        enable_xh2_stable_output=args.enable_xh2_stable_output,
        cpp_backend="v2",
        llm_opt=True,
        parallel_jobs=args.j,
    )

    Xh2Exec.build_from_hmonnx(
        hmonnx=find_hmonnx_file(str(decode_dir)),
        hmm_name=f"{model_prefix}_decode",
        output=str(output_dir),
        llm_batch=args.batch,
        flash_attn=llm_flash_attention,
        context_length=args.context_length,
        ndevice=args.ndevice,
        ncore=args.ncore,
        enable_xh2_stable_output=args.enable_xh2_stable_output,
        cpp_backend="v2",
        llm_opt=True,
        parallel_jobs=args.j,
    )

    print(f"Compiled MiniCPM-V 4.5 models to: {output_dir.resolve()}")


if __name__ == "__main__":
    main()
