cmake_minimum_required(VERSION 3.16.3)
project(tcim_yolov3_example)

unset(TVM_LIBRARY CACHE)
set(TCIM_PATH "../../../../itvm/build/install")
if(DEFINED ENV{HDPL_TOOLCHAIN_ITVM_INSTALL})
  set(TCIM_PATH $ENV{HDPL_TOOLCHAIN_ITVM_INSTALL})
endif()
if(DEFINED ENV{TCIM_PATH})
  set(TCIM_PATH $ENV{TCIM_PATH})
endif()
message(STATUS "TCIM_PATH: " ${TCIM_PATH})
find_library(TVM_LIBRARY NAMES tvm PATHS ${TCIM_PATH} NO_DEFAULT_PATH)
if(NOT DEFINED ${TVM_LIBRARY})
  find_library(TVM_LIBRARY NAMES tvm PATHS ${TCIM_PATH}/lib NO_DEFAULT_PATH)
endif()

if(DEFINED ENV{HOUMO_PATH})
  set(HDPL_INSTALL_PATH $ENV{HOUMO_PATH})
else()
  set(HDPL_INSTALL_PATH $ENV{HDPL_PATH})
endif()

if(NOT DEFINED ${HDPL_LIBRARY})
  find_library(HDPL_LIBRARY NAMES hdplrt PATHS ${HDPL_INSTALL_PATH}/lib NO_DEFAULT_PATH)
endif()

include_directories(${HDPL_INSTALL_PATH}/include)
include_directories(${TCIM_PATH}/include)

add_definitions(-w)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -O2")
file(GLOB HDPL_YOLOV3_SRCS *.cc)
add_executable(hdpl_yolov3 ${HDPL_YOLOV3_SRCS})
target_link_libraries(hdpl_yolov3 ${TVM_LIBRARY} ${HDPL_LIBRARY} -pthread dl gomp)
