default_model_name: "qwen3-next"
default_model_size: "80b-a3b"

model_configs:
  qwen3-next:
    "80b-a3b":
      modelscope_repo: ["Qwen/Qwen3-Next-80B-A3B-Instruct"]
      model_name: "qwen3-next"
      model_size: "80b-a3b"
      ncore: 2
      quant_type: "w4a8"
      context_length: "256k"
      ndevice: 2
      batch: 1
      prefill_length: 256
      workflow_config: "workflows/xh2a/llm_models/qwen3_next/80b_a3b/qwen3_next_80b_a3b_full_gptq.yaml"
