model: {
  framework: onnx,
  name: resnet50,
  save_dir: ./output,
  weight: ./resnet50.onnx,
  inputs: [
    {
      name: input.1,
      shape: [1, 3, 224, 224],
      layout: NCHW,
      format: RGB,
      image: {
        format: YUV422,
        size: ,
        crop: ,
      },
      dtype: uint8,
      mean: [ 0.485, 0.456, 0.406 ],
      std: [ 0.229, 0.224, 0.225 ],
    }
  ],
  impl_class: Resnet50,
}

quant: {
  # ptq_cfg_path: ./compile_model/quant_config.py,
  calib_dir: imagenet,
  calib_num: 20,
  debug_level: 1,
  calib_method: ,
}

build: {
  opt_level: 0,
}

test: {
  data_path: imagenet/ILSVRC2012_val_00000016.JPEG,
}

demo: {
  data_dir: imagenet,
  test_num: 10,
}

perf: {
  # data_dir: imagenet,
  test_num: 1000,
  mode: throughput,
  end2end: ,
}

accuracy: {
  data_dir: imagenet,
  test_num: 0,
  dataset_class: Dataset,
}

