
cmake_minimum_required(VERSION 3.16.3)
project(tcim_pointpillars_demo)
unset(TVM_LIBRARY CACHE)
if(DEFINED ENV{HOUMO_PATH})
  set(HOUMO_PATH $ENV{HOUMO_PATH})
endif()
if(DEFINED ENV{TCIM_PATH})
  message(STATUS "TCIM_PATH: " $ENV{TCIM_PATH})
  set(TCIM_PATH $ENV{TCIM_PATH})
endif()
if(NOT DEFINED ${HDPL_LIBRARY})
  find_library(HDPL_LIBRARY NAMES hdplrt PATHS ${HOUMO_PATH}/lib NO_DEFAULT_PATH)
endif()
if(NOT DEFINED ${IDNNL_LIBRARY})
  find_library(IDNNL_LIBRARY NAMES idnnl PATHS ${HOUMO_PATH}/lib NO_DEFAULT_PATH)
endif()
find_library(TVM_LIBRARY NAMES tvm PATHS ${TCIM_PATH} NO_DEFAULT_PATH)
if(NOT DEFINED ${TVM_LIBRARY})
  find_library(TVM_LIBRARY NAMES tvm PATHS ${TCIM_PATH}/lib NO_DEFAULT_PATH)
endif()
include_directories(${HOUMO_PATH}/include)
include_directories(${TCIM_PATH}/include)
add_definitions(-w)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -O0 -g")
add_executable(hdpl_pointpillars_run hdpl_pointpillars_run.cc)
target_link_libraries(hdpl_pointpillars_run ${OpenCV_LIBS})
target_link_libraries(hdpl_pointpillars_run ${IDNNL_LIBRARY})
target_link_libraries(hdpl_pointpillars_run ${HDPL_LIBRARY})
target_link_libraries(hdpl_pointpillars_run ${TVM_LIBRARY} -pthread dl gomp)
