Streams:
  - ModelName: Qwen3-30B-A3B
    prefill: output/xh2/qwen3_prefill.hmm
    decode: output/xh2/qwen3_decode.hmm
    embedding: output/xh2/hmquant/quant_embedding.bin
    input: 256
    output: 256
    loop: 1
    batch: 1
    LazyMode: ''
    no_warm_up: ''
  - ModelName: Qwen3-30B-A3B
    prefill: output/xh2/qwen3_prefill.hmm
    decode: output/xh2/qwen3_decode.hmm
    embedding: output/xh2/hmquant/quant_embedding.bin
    input: 1024
    output: 256
    loop: 1
    batch: 1
    LazyMode: ''
    no_warm_up: ''
  - ModelName: Qwen3-30B-A3B
    prefill: output/xh2/qwen3_prefill.hmm
    decode: output/xh2/qwen3_decode.hmm
    embedding: output/xh2/hmquant/quant_embedding.bin
    input: 2048
    output: 256
    loop: 1
    batch: 1
    LazyMode: ''
    no_warm_up: ''

dump_file: perf_result.yaml