default_model_name: "qwen3"
default_model_size: "30b-a3b"

model_configs:
  qwen3:
    "30b-a3b":
      modelscope_repo: ["qwen/qwen3-30b-a3b"]
      model_name: "qwen3"
      model_size: "30b-a3b"
      ncore: 2
      quant_type: "w4a8h0_ssfp"
      context_length: "32k"
      ndevice: 1
      batch: 1
      prefill_length: 256
