model:
  name: custom_multi_input
  save_dir: output
  model_path: custom_multi_input.onnx
  inputs:
    x:
      shape: [1, 4, 4]  # NCHW
      data_format: null
    y:
      shape: [1, 4, 4]  # NCHW
      data_format: null

quant:
  calib_data: data
  calib_num: 50

build:
  ncore: 1
  opt_level: 2

