default_model_name: "gemma4"
default_model_size: "e2b"

model_configs:
  gemma4:
    "26b-a4b":
      modelscope_repo: ["google/gemma-4-26B-A4B-it"]
      model_name: "gemma4"
      model_size: "26b-a4b"
      ncore: 2
      context_length: "128k"
      ndevice: 1
      batch: 1
      prefill_length: 256

    "e2b":
      modelscope_repo: ["google/gemma-4-E2B-it"]
      model_name: "gemma4"
      model_size: "e2b"
      ncore: 2
      context_length: "128k"
      ndevice: 1
      batch: 1
      prefill_length: 256

    "e4b":
      modelscope_repo: ["google/gemma-4-E4B-it"]
      model_name: "gemma4"
      model_size: "e4b"
      ncore: 2
      context_length: "128k"
      ndevice: 1
      batch: 1
      prefill_length: 256

    "31b":
      modelscope_repo: ["google/gemma-4-31B-it"]
      model_name: "gemma4"
      model_size: "31b"
      ncore: 2
      context_length: "256k"
      ndevice: 2
      batch: 1
      prefill_length: 256