default_model_name: "gemma4"
default_model_size: "26b-a4b"

model_configs:
  gemma4:
    "26b-a4b":
      modelscope_repo: ["google/gemma-4-26B-A4B-it"]
      model_name: "gemma4"
      model_size: "26b-a4b"
      ncore: 2
      context_length: "128k"
      ndevice: 1
      batch: 1
      prefill_length: 256
      max_size_w: 448
      max_size_h: 448