default_model_name: "qwen2.5"
default_model_size: "7b"

model_configs:
  qwen2.5:
    "7b":
      modelscope_repo: ["Qwen/Qwen2.5-7B-Instruct"]
      model_name: "qwen2.5"
      model_size: "7b"
      ncore: 2
      quant_type: "w4a8h0_ssfp"
      context_length: "8k"
      ndevice: 1
      batch: 1
      prefill_length: 256
