# Copyright (c) 2025 HOUMO AI
#
# File: test_compile_models.py
# Description:
#  Model Compilation Tests Module.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Generated by update_test_py.py. Do not edit manually.

import logging

import pytest

from .test_models_utils import execute_compile_flow

logger = logging.getLogger(__name__)


def _compile_func(model_name: str, setup_logging) -> None:
    """Execute model compilation test for a specific model."""
    logger.info("===> TEST START: test_%s_compile", model_name)
    execute_compile_flow(model_name, setup_logging)


@pytest.mark.bge
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_embedding_bge_compile",
    depends_on=["test_quant_models.py::test_embedding_bge_quant"],
)
def test_embedding_bge_compile(setup_logging) -> None:
    """test_embedding_bge_compile"""
    _compile_func("bge", setup_logging)


@pytest.mark.cam
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_cam_compile",
    depends_on=["test_quant_models.py::test_asr_cam_quant"],
)
def test_asr_cam_compile(setup_logging) -> None:
    """test_asr_cam_compile"""
    _compile_func("cam", setup_logging)


@pytest.mark.copaw_flash
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_copaw_flash_compile",
    depends_on=["test_quant_models.py::test_llm_copaw_flash_quant"],
)
def test_llm_copaw_flash_compile(setup_logging) -> None:
    """test_llm_copaw_flash_compile"""
    _compile_func("copaw-flash", setup_logging)


@pytest.mark.cosyvoice3
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_tts_cosyvoice3_compile",
    depends_on=["test_quant_models.py::test_tts_cosyvoice3_quant"],
)
def test_tts_cosyvoice3_compile(setup_logging) -> None:
    """test_tts_cosyvoice3_compile"""
    _compile_func("cosyvoice3", setup_logging)


@pytest.mark.ct_transformer
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_ct_transformer_compile",
    depends_on=["test_quant_models.py::test_asr_ct_transformer_quant"],
)
def test_asr_ct_transformer_compile(setup_logging) -> None:
    """test_asr_ct_transformer_compile"""
    _compile_func("ct_transformer", setup_logging)


@pytest.mark.deepseek_r1_qwen3_8b
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_deepseek_r1_qwen3_8b_compile",
    depends_on=["test_quant_models.py::test_llm_deepseek_r1_qwen3_8b_quant"],
)
def test_llm_deepseek_r1_qwen3_8b_compile(setup_logging) -> None:
    """test_llm_deepseek_r1_qwen3_8b_compile"""
    _compile_func("deepseek-r1-qwen3-8b", setup_logging)


@pytest.mark.deepseek
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_deepseek_compile",
    depends_on=["test_get_models.py::test_llm_deepseek_get_model"],
)
def test_llm_deepseek_compile(setup_logging) -> None:
    """test_llm_deepseek_compile"""
    _compile_func("deepseek", setup_logging)


@pytest.mark.dinov3_base
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_backbone_dinov3_base_compile",
    depends_on=["test_quant_models.py::test_backbone_dinov3_base_quant"],
)
def test_backbone_dinov3_base_compile(setup_logging) -> None:
    """test_backbone_dinov3_base_compile"""
    _compile_func("dinov3-base", setup_logging)


@pytest.mark.efficientnet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_backbone_efficientnet_compile",
    depends_on=["test_quant_models.py::test_backbone_efficientnet_quant"],
)
def test_backbone_efficientnet_compile(setup_logging) -> None:
    """test_backbone_efficientnet_compile"""
    _compile_func("efficientnet", setup_logging)


@pytest.mark.emotion2vec
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_emotion2vec_compile",
    depends_on=["test_quant_models.py::test_asr_emotion2vec_quant"],
)
def test_asr_emotion2vec_compile(setup_logging) -> None:
    """test_asr_emotion2vec_compile"""
    _compile_func("emotion2vec", setup_logging)


@pytest.mark.gemma4
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_48g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_vlm_gemma4_compile",
    depends_on=["test_quant_models.py::test_vlm_gemma4_quant"],
)
def test_vlm_gemma4_compile(setup_logging) -> None:
    """test_vlm_gemma4_compile"""
    _compile_func("gemma4", setup_logging)


@pytest.mark.glm_asr
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_glm_asr_compile",
    depends_on=["test_quant_models.py::test_asr_glm_asr_quant"],
)
def test_asr_glm_asr_compile(setup_logging) -> None:
    """test_asr_glm_asr_compile"""
    _compile_func("glm-asr", setup_logging)


@pytest.mark.glm_ocr
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_ocr_glm_ocr_compile",
    depends_on=["test_quant_models.py::test_ocr_glm_ocr_quant"],
)
def test_ocr_glm_ocr_compile(setup_logging) -> None:
    """test_ocr_glm_ocr_compile"""
    _compile_func("glm-ocr", setup_logging)


@pytest.mark.gpt_oss
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_gpt_oss_compile",
    depends_on=["test_get_models.py::test_llm_gpt_oss_get_model"],
)
def test_llm_gpt_oss_compile(setup_logging) -> None:
    """test_llm_gpt_oss_compile"""
    _compile_func("gpt-oss", setup_logging)


@pytest.mark.gte
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_embedding_gte_compile",
    depends_on=["test_quant_models.py::test_embedding_gte_quant"],
)
def test_embedding_gte_compile(setup_logging) -> None:
    """test_embedding_gte_compile"""
    _compile_func("gte", setup_logging)


@pytest.mark.lprnet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_ocr_lprnet_compile",
    depends_on=["test_quant_models.py::test_ocr_lprnet_quant"],
)
def test_ocr_lprnet_compile(setup_logging) -> None:
    """test_ocr_lprnet_compile"""
    _compile_func("lprnet", setup_logging)


@pytest.mark.mineru2dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_ocr_mineru2dot5_compile",
    depends_on=["test_quant_models.py::test_ocr_mineru2dot5_quant"],
)
def test_ocr_mineru2dot5_compile(setup_logging) -> None:
    """test_ocr_mineru2dot5_compile"""
    _compile_func("mineru2.5", setup_logging)


@pytest.mark.minicpm_v_4dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_vlm_minicpm_v_4dot5_compile",
    depends_on=["test_quant_models.py::test_vlm_minicpm_v_4dot5_quant"],
)
def test_vlm_minicpm_v_4dot5_compile(setup_logging) -> None:
    """test_vlm_minicpm_v_4dot5_compile"""
    _compile_func("minicpm-v-4.5", setup_logging)


@pytest.mark.minicpm_v_4dot6
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_vlm_minicpm_v_4dot6_compile",
    depends_on=["test_quant_models.py::test_vlm_minicpm_v_4dot6_quant"],
)
def test_vlm_minicpm_v_4dot6_compile(setup_logging) -> None:
    """test_vlm_minicpm_v_4dot6_compile"""
    _compile_func("minicpm-v-4.6", setup_logging)


@pytest.mark.minicpmo
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_omni_minicpmo_compile",
    depends_on=["test_quant_models.py::test_omni_minicpmo_quant"],
)
def test_omni_minicpmo_compile(setup_logging) -> None:
    """test_omni_minicpmo_compile"""
    _compile_func("minicpmo", setup_logging)


@pytest.mark.mobilenetv2
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_backbone_mobilenetv2_compile",
    depends_on=["test_quant_models.py::test_backbone_mobilenetv2_quant"],
)
def test_backbone_mobilenetv2_compile(setup_logging) -> None:
    """test_backbone_mobilenetv2_compile"""
    _compile_func("mobilenetv2", setup_logging)


@pytest.mark.ornith1dot0
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_vlm_ornith1dot0_compile",
    depends_on=["test_quant_models.py::test_vlm_ornith1dot0_quant"],
)
def test_vlm_ornith1dot0_compile(setup_logging) -> None:
    """test_vlm_ornith1dot0_compile"""
    _compile_func("ornith1.0", setup_logging)


@pytest.mark.paddleocr_vl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_ocr_paddleocr_vl_compile",
    depends_on=["test_quant_models.py::test_ocr_paddleocr_vl_quant"],
)
def test_ocr_paddleocr_vl_compile(setup_logging) -> None:
    """test_ocr_paddleocr_vl_compile"""
    _compile_func("paddleocr-vl", setup_logging)


@pytest.mark.paddleocr_v5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_ocr_paddleocr_v5_compile",
    depends_on=["test_quant_models.py::test_ocr_paddleocr_v5_quant"],
)
def test_ocr_paddleocr_v5_compile(setup_logging) -> None:
    """test_ocr_paddleocr_v5_compile"""
    _compile_func("paddleocr_v5", setup_logging)


@pytest.mark.ppocrv3_det
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_ocr_ppocrv3_det_compile",
    depends_on=["test_quant_models.py::test_ocr_ppocrv3_det_quant"],
)
def test_ocr_ppocrv3_det_compile(setup_logging) -> None:
    """test_ocr_ppocrv3_det_compile"""
    _compile_func("ppocrv3_det", setup_logging)


@pytest.mark.ppocrv3_rec
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_ocr_ppocrv3_rec_compile",
    depends_on=["test_quant_models.py::test_ocr_ppocrv3_rec_quant"],
)
def test_ocr_ppocrv3_rec_compile(setup_logging) -> None:
    """test_ocr_ppocrv3_rec_compile"""
    _compile_func("ppocrv3_rec", setup_logging)


@pytest.mark.qwen_agentworld
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_qwen_agentworld_compile",
    depends_on=["test_quant_models.py::test_llm_qwen_agentworld_quant"],
)
def test_llm_qwen_agentworld_compile(setup_logging) -> None:
    """test_llm_qwen_agentworld_compile"""
    _compile_func("qwen-agentworld", setup_logging)


@pytest.mark.qwen2dot5_vl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_vlm_qwen2dot5_vl_compile",
    depends_on=["test_quant_models.py::test_vlm_qwen2dot5_vl_quant"],
)
def test_vlm_qwen2dot5_vl_compile(setup_logging) -> None:
    """test_vlm_qwen2dot5_vl_compile"""
    _compile_func("qwen2.5-vl", setup_logging)


@pytest.mark.qwen2dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_qwen2dot5_compile",
    depends_on=["test_quant_models.py::test_llm_qwen2dot5_quant"],
)
def test_llm_qwen2dot5_compile(setup_logging) -> None:
    """test_llm_qwen2dot5_compile"""
    _compile_func("qwen2.5", setup_logging)


@pytest.mark.qwen3_30b_a3b
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_qwen3_30b_a3b_compile",
    depends_on=["test_quant_models.py::test_llm_qwen3_30b_a3b_quant"],
)
def test_llm_qwen3_30b_a3b_compile(setup_logging) -> None:
    """test_llm_qwen3_30b_a3b_compile"""
    _compile_func("qwen3-30b-a3b", setup_logging)


@pytest.mark.qwen3_asr
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_qwen3_asr_compile",
    depends_on=["test_quant_models.py::test_asr_qwen3_asr_quant"],
)
def test_asr_qwen3_asr_compile(setup_logging) -> None:
    """test_asr_qwen3_asr_compile"""
    _compile_func("qwen3-asr", setup_logging)


@pytest.mark.qwen3_embedding
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_embedding_qwen3_embedding_compile",
    depends_on=["test_quant_models.py::test_embedding_qwen3_embedding_quant"],
)
def test_embedding_qwen3_embedding_compile(setup_logging) -> None:
    """test_embedding_qwen3_embedding_compile"""
    _compile_func("qwen3-embedding", setup_logging)


@pytest.mark.qwen3_forcealigner
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_qwen3_forcealigner_compile",
    depends_on=["test_quant_models.py::test_asr_qwen3_forcealigner_quant"],
)
def test_asr_qwen3_forcealigner_compile(setup_logging) -> None:
    """test_asr_qwen3_forcealigner_compile"""
    _compile_func("qwen3-forcealigner", setup_logging)


@pytest.mark.qwen3_next
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_48g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_qwen3_next_compile",
    depends_on=["test_quant_models.py::test_llm_qwen3_next_quant"],
)
def test_llm_qwen3_next_compile(setup_logging) -> None:
    """test_llm_qwen3_next_compile"""
    _compile_func("qwen3-next", setup_logging)


@pytest.mark.qwen3_omni
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_omni_qwen3_omni_compile",
    depends_on=["test_quant_models.py::test_omni_qwen3_omni_quant"],
)
def test_omni_qwen3_omni_compile(setup_logging) -> None:
    """test_omni_qwen3_omni_compile"""
    _compile_func("qwen3-omni", setup_logging)


@pytest.mark.qwen3_reranker
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_reranker_qwen3_reranker_compile",
    depends_on=["test_quant_models.py::test_reranker_qwen3_reranker_quant"],
)
def test_reranker_qwen3_reranker_compile(setup_logging) -> None:
    """test_reranker_qwen3_reranker_compile"""
    _compile_func("qwen3-reranker", setup_logging)


@pytest.mark.qwen3_tts
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_tts_qwen3_tts_compile",
    depends_on=["test_quant_models.py::test_tts_qwen3_tts_quant"],
)
def test_tts_qwen3_tts_compile(setup_logging) -> None:
    """test_tts_qwen3_tts_compile"""
    _compile_func("qwen3-tts", setup_logging)


@pytest.mark.qwen3_vl_embedding
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_embedding_qwen3_vl_embedding_compile",
    depends_on=["test_quant_models.py::test_embedding_qwen3_vl_embedding_quant"],
)
def test_embedding_qwen3_vl_embedding_compile(setup_logging) -> None:
    """test_embedding_qwen3_vl_embedding_compile"""
    _compile_func("qwen3-vl-embedding", setup_logging)


@pytest.mark.qwen3_vl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_vlm_qwen3_vl_compile",
    depends_on=["test_quant_models.py::test_vlm_qwen3_vl_quant"],
)
def test_vlm_qwen3_vl_compile(setup_logging) -> None:
    """test_vlm_qwen3_vl_compile"""
    _compile_func("qwen3-vl", setup_logging)


@pytest.mark.qwen3dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_qwen3dot5_compile",
    depends_on=["test_quant_models.py::test_llm_qwen3dot5_quant"],
)
def test_llm_qwen3dot5_compile(setup_logging) -> None:
    """test_llm_qwen3dot5_compile"""
    _compile_func("qwen3.5", setup_logging)


@pytest.mark.qwen3
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_llm_qwen3_compile",
    depends_on=["test_quant_models.py::test_llm_qwen3_quant"],
)
def test_llm_qwen3_compile(setup_logging) -> None:
    """test_llm_qwen3_compile"""
    _compile_func("qwen3", setup_logging)


@pytest.mark.resnet50
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_backbone_resnet50_compile",
    depends_on=["test_quant_models.py::test_backbone_resnet50_quant"],
)
def test_backbone_resnet50_compile(setup_logging) -> None:
    """test_backbone_resnet50_compile"""
    _compile_func("resnet50", setup_logging)


@pytest.mark.sam2
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_segmentation_sam2_compile",
    depends_on=["test_quant_models.py::test_segmentation_sam2_quant"],
)
def test_segmentation_sam2_compile(setup_logging) -> None:
    """test_segmentation_sam2_compile"""
    _compile_func("sam2", setup_logging)


@pytest.mark.sam3
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_segmentation_sam3_compile",
    depends_on=["test_quant_models.py::test_segmentation_sam3_quant"],
)
def test_segmentation_sam3_compile(setup_logging) -> None:
    """test_segmentation_sam3_compile"""
    _compile_func("sam3", setup_logging)


@pytest.mark.sdxl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_diffusion_sdxl_compile",
    depends_on=["test_get_models.py::test_diffusion_sdxl_get_model"],
)
def test_diffusion_sdxl_compile(setup_logging) -> None:
    """test_diffusion_sdxl_compile"""
    _compile_func("sdxl", setup_logging)


@pytest.mark.sensevoice
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_sensevoice_compile",
    depends_on=["test_quant_models.py::test_asr_sensevoice_quant"],
)
def test_asr_sensevoice_compile(setup_logging) -> None:
    """test_asr_sensevoice_compile"""
    _compile_func("sensevoice", setup_logging)


@pytest.mark.siglip2
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_embedding_siglip2_compile",
    depends_on=["test_quant_models.py::test_embedding_siglip2_quant"],
)
def test_embedding_siglip2_compile(setup_logging) -> None:
    """test_embedding_siglip2_compile"""
    _compile_func("siglip2", setup_logging)


@pytest.mark.vit
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_backbone_vit_compile",
    depends_on=["test_quant_models.py::test_backbone_vit_quant"],
)
def test_backbone_vit_compile(setup_logging) -> None:
    """test_backbone_vit_compile"""
    _compile_func("vit", setup_logging)


@pytest.mark.wenet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_wenet_compile",
    depends_on=["test_get_models.py::test_asr_wenet_get_model"],
)
def test_asr_wenet_compile(setup_logging) -> None:
    """test_asr_wenet_compile"""
    _compile_func("wenet", setup_logging)


@pytest.mark.whisper
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_asr_whisper_compile",
    depends_on=["test_quant_models.py::test_asr_whisper_quant"],
)
def test_asr_whisper_compile(setup_logging) -> None:
    """test_asr_whisper_compile"""
    _compile_func("whisper", setup_logging)


@pytest.mark.yolo11m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolo11m_compile",
    depends_on=["test_quant_models.py::test_detection_yolo11m_quant"],
)
def test_detection_yolo11m_compile(setup_logging) -> None:
    """test_detection_yolo11m_compile"""
    _compile_func("yolo11m", setup_logging)


@pytest.mark.yolo12m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolo12m_compile",
    depends_on=["test_quant_models.py::test_detection_yolo12m_quant"],
)
def test_detection_yolo12m_compile(setup_logging) -> None:
    """test_detection_yolo12m_compile"""
    _compile_func("yolo12m", setup_logging)


@pytest.mark.yolo26m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolo26m_compile",
    depends_on=["test_quant_models.py::test_detection_yolo26m_quant"],
)
def test_detection_yolo26m_compile(setup_logging) -> None:
    """test_detection_yolo26m_compile"""
    _compile_func("yolo26m", setup_logging)


@pytest.mark.yolop
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_autodrive_yolop_compile",
    depends_on=["test_quant_models.py::test_autodrive_yolop_quant"],
)
def test_autodrive_yolop_compile(setup_logging) -> None:
    """test_autodrive_yolop_compile"""
    _compile_func("yolop", setup_logging)


@pytest.mark.yolov10m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolov10m_compile",
    depends_on=["test_quant_models.py::test_detection_yolov10m_quant"],
)
def test_detection_yolov10m_compile(setup_logging) -> None:
    """test_detection_yolov10m_compile"""
    _compile_func("yolov10m", setup_logging)


@pytest.mark.yolov3
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolov3_compile",
    depends_on=["test_quant_models.py::test_detection_yolov3_quant"],
)
def test_detection_yolov3_compile(setup_logging) -> None:
    """test_detection_yolov3_compile"""
    _compile_func("yolov3", setup_logging)


@pytest.mark.yolov5m_face
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolov5m_face_compile",
    depends_on=["test_quant_models.py::test_detection_yolov5m_face_quant"],
)
def test_detection_yolov5m_face_compile(setup_logging) -> None:
    """test_detection_yolov5m_face_compile"""
    _compile_func("yolov5m_face", setup_logging)


@pytest.mark.yolov5s
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolov5s_compile",
    depends_on=["test_quant_models.py::test_detection_yolov5s_quant"],
)
def test_detection_yolov5s_compile(setup_logging) -> None:
    """test_detection_yolov5s_compile"""
    _compile_func("yolov5s", setup_logging)


@pytest.mark.yolov5s_feature
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolov5s_feature_compile",
    depends_on=["test_quant_models.py::test_detection_yolov5s_feature_quant"],
)
def test_detection_yolov5s_feature_compile(setup_logging) -> None:
    """test_detection_yolov5s_feature_compile"""
    _compile_func("yolov5s_feature", setup_logging)


@pytest.mark.yolov7
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolov7_compile",
    depends_on=["test_quant_models.py::test_detection_yolov7_quant"],
)
def test_detection_yolov7_compile(setup_logging) -> None:
    """test_detection_yolov7_compile"""
    _compile_func("yolov7", setup_logging)


@pytest.mark.yolov8m_cls
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_backbone_yolov8m_cls_compile",
    depends_on=["test_quant_models.py::test_backbone_yolov8m_cls_quant"],
)
def test_backbone_yolov8m_cls_compile(setup_logging) -> None:
    """test_backbone_yolov8m_cls_compile"""
    _compile_func("yolov8m-cls", setup_logging)


@pytest.mark.yolov8m_pose
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_estimation_yolov8m_pose_compile",
    depends_on=["test_quant_models.py::test_estimation_yolov8m_pose_quant"],
)
def test_estimation_yolov8m_pose_compile(setup_logging) -> None:
    """test_estimation_yolov8m_pose_compile"""
    _compile_func("yolov8m-pose", setup_logging)


@pytest.mark.yolov8m_seg
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_segmentation_yolov8m_seg_compile",
    depends_on=["test_quant_models.py::test_segmentation_yolov8m_seg_quant"],
)
def test_segmentation_yolov8m_seg_compile(setup_logging) -> None:
    """test_segmentation_yolov8m_seg_compile"""
    _compile_func("yolov8m-seg", setup_logging)


@pytest.mark.yolov8m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolov8m_compile",
    depends_on=["test_quant_models.py::test_detection_yolov8m_quant"],
)
def test_detection_yolov8m_compile(setup_logging) -> None:
    """test_detection_yolov8m_compile"""
    _compile_func("yolov8m", setup_logging)


@pytest.mark.yolov9m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolov9m_compile",
    depends_on=["test_quant_models.py::test_detection_yolov9m_quant"],
)
def test_detection_yolov9m_compile(setup_logging) -> None:
    """test_detection_yolov9m_compile"""
    _compile_func("yolov9m", setup_logging)


@pytest.mark.yolox
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_detection_yolox_compile",
    depends_on=["test_quant_models.py::test_detection_yolox_quant"],
)
def test_detection_yolox_compile(setup_logging) -> None:
    """test_detection_yolox_compile"""
    _compile_func("yolox", setup_logging)


@pytest.mark.z_image_turbo
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.compile
@pytest.mark.dependency(
    name="test_compile_models.py::test_diffusion_z_image_turbo_compile",
    depends_on=["test_quant_models.py::test_diffusion_z_image_turbo_quant"],
)
def test_diffusion_z_image_turbo_compile(setup_logging) -> None:
    """test_diffusion_z_image_turbo_compile"""
    _compile_func("z-image-turbo", setup_logging)




