# Copyright (c) 2025 HOUMO AI
#
# File: test_get_models.py
# Description:
#  Model Downloading Tests Module.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Generated by update_test_py.py. Do not edit manually.

import logging

import pytest

from .test_models_utils import execute_get_model_flow

logger = logging.getLogger(__name__)


def _get_model_func(model_name: str, setup_logging) -> None:
    """Execute model downloading test for a specific model."""
    logger.info("===> TEST START: test_%s_get_model", model_name)
    execute_get_model_flow(model_name, setup_logging)


@pytest.mark.bge
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_embedding_bge_get_model")
def test_embedding_bge_get_model(setup_logging) -> None:
    """test_embedding_bge_get_model"""
    _get_model_func("bge", setup_logging)


@pytest.mark.cam
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_cam_get_model")
def test_asr_cam_get_model(setup_logging) -> None:
    """test_asr_cam_get_model"""
    _get_model_func("cam", setup_logging)


@pytest.mark.copaw_flash
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_copaw_flash_get_model")
def test_llm_copaw_flash_get_model(setup_logging) -> None:
    """test_llm_copaw_flash_get_model"""
    _get_model_func("copaw-flash", setup_logging)


@pytest.mark.cosyvoice3
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_tts_cosyvoice3_get_model")
def test_tts_cosyvoice3_get_model(setup_logging) -> None:
    """test_tts_cosyvoice3_get_model"""
    _get_model_func("cosyvoice3", setup_logging)


@pytest.mark.ct_transformer
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_ct_transformer_get_model")
def test_asr_ct_transformer_get_model(setup_logging) -> None:
    """test_asr_ct_transformer_get_model"""
    _get_model_func("ct_transformer", setup_logging)


@pytest.mark.deepseek_r1_qwen3_8b
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_deepseek_r1_qwen3_8b_get_model")
def test_llm_deepseek_r1_qwen3_8b_get_model(setup_logging) -> None:
    """test_llm_deepseek_r1_qwen3_8b_get_model"""
    _get_model_func("deepseek-r1-qwen3-8b", setup_logging)


@pytest.mark.deepseek
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_deepseek_get_model")
def test_llm_deepseek_get_model(setup_logging) -> None:
    """test_llm_deepseek_get_model"""
    _get_model_func("deepseek", setup_logging)


@pytest.mark.dinov3_base
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_backbone_dinov3_base_get_model")
def test_backbone_dinov3_base_get_model(setup_logging) -> None:
    """test_backbone_dinov3_base_get_model"""
    _get_model_func("dinov3-base", setup_logging)


@pytest.mark.efficientnet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_backbone_efficientnet_get_model")
def test_backbone_efficientnet_get_model(setup_logging) -> None:
    """test_backbone_efficientnet_get_model"""
    _get_model_func("efficientnet", setup_logging)


@pytest.mark.emotion2vec
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_emotion2vec_get_model")
def test_asr_emotion2vec_get_model(setup_logging) -> None:
    """test_asr_emotion2vec_get_model"""
    _get_model_func("emotion2vec", setup_logging)


@pytest.mark.funaudiochat
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_lalm_funaudiochat_get_model")
def test_lalm_funaudiochat_get_model(setup_logging) -> None:
    """test_lalm_funaudiochat_get_model"""
    _get_model_func("funaudiochat", setup_logging)


@pytest.mark.gemma4
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_48g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_vlm_gemma4_get_model")
def test_vlm_gemma4_get_model(setup_logging) -> None:
    """test_vlm_gemma4_get_model"""
    _get_model_func("gemma4", setup_logging)


@pytest.mark.glm_asr
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_glm_asr_get_model")
def test_asr_glm_asr_get_model(setup_logging) -> None:
    """test_asr_glm_asr_get_model"""
    _get_model_func("glm-asr", setup_logging)


@pytest.mark.glm_ocr
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_ocr_glm_ocr_get_model")
def test_ocr_glm_ocr_get_model(setup_logging) -> None:
    """test_ocr_glm_ocr_get_model"""
    _get_model_func("glm-ocr", setup_logging)


@pytest.mark.gpt_oss
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_gpt_oss_get_model")
def test_llm_gpt_oss_get_model(setup_logging) -> None:
    """test_llm_gpt_oss_get_model"""
    _get_model_func("gpt-oss", setup_logging)


@pytest.mark.gte
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_embedding_gte_get_model")
def test_embedding_gte_get_model(setup_logging) -> None:
    """test_embedding_gte_get_model"""
    _get_model_func("gte", setup_logging)


@pytest.mark.lprnet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_ocr_lprnet_get_model")
def test_ocr_lprnet_get_model(setup_logging) -> None:
    """test_ocr_lprnet_get_model"""
    _get_model_func("lprnet", setup_logging)


@pytest.mark.mineru2dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_ocr_mineru2dot5_get_model")
def test_ocr_mineru2dot5_get_model(setup_logging) -> None:
    """test_ocr_mineru2dot5_get_model"""
    _get_model_func("mineru2.5", setup_logging)


@pytest.mark.minicpm_v_4dot6
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_vlm_minicpm_v_4dot6_get_model")
def test_vlm_minicpm_v_4dot6_get_model(setup_logging) -> None:
    """test_vlm_minicpm_v_4dot6_get_model"""
    _get_model_func("minicpm-v-4.6", setup_logging)


@pytest.mark.minicpmo
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_omni_minicpmo_get_model")
def test_omni_minicpmo_get_model(setup_logging) -> None:
    """test_omni_minicpmo_get_model"""
    _get_model_func("minicpmo", setup_logging)


@pytest.mark.mobilenetv2
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_backbone_mobilenetv2_get_model")
def test_backbone_mobilenetv2_get_model(setup_logging) -> None:
    """test_backbone_mobilenetv2_get_model"""
    _get_model_func("mobilenetv2", setup_logging)


@pytest.mark.paddleocr_vl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_ocr_paddleocr_vl_get_model")
def test_ocr_paddleocr_vl_get_model(setup_logging) -> None:
    """test_ocr_paddleocr_vl_get_model"""
    _get_model_func("paddleocr-vl", setup_logging)


@pytest.mark.ppocrv3_det
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_ocr_ppocrv3_det_get_model")
def test_ocr_ppocrv3_det_get_model(setup_logging) -> None:
    """test_ocr_ppocrv3_det_get_model"""
    _get_model_func("ppocrv3_det", setup_logging)


@pytest.mark.ppocrv3_rec
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_ocr_ppocrv3_rec_get_model")
def test_ocr_ppocrv3_rec_get_model(setup_logging) -> None:
    """test_ocr_ppocrv3_rec_get_model"""
    _get_model_func("ppocrv3_rec", setup_logging)


@pytest.mark.qwen2dot5_vl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_vlm_qwen2dot5_vl_get_model")
def test_vlm_qwen2dot5_vl_get_model(setup_logging) -> None:
    """test_vlm_qwen2dot5_vl_get_model"""
    _get_model_func("qwen2.5-vl", setup_logging)


@pytest.mark.qwen2dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_qwen2dot5_get_model")
def test_llm_qwen2dot5_get_model(setup_logging) -> None:
    """test_llm_qwen2dot5_get_model"""
    _get_model_func("qwen2.5", setup_logging)


@pytest.mark.qwen3_30b_a3b
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_qwen3_30b_a3b_get_model")
def test_llm_qwen3_30b_a3b_get_model(setup_logging) -> None:
    """test_llm_qwen3_30b_a3b_get_model"""
    _get_model_func("qwen3-30b-a3b", setup_logging)


@pytest.mark.qwen3_asr
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_qwen3_asr_get_model")
def test_asr_qwen3_asr_get_model(setup_logging) -> None:
    """test_asr_qwen3_asr_get_model"""
    _get_model_func("qwen3-asr", setup_logging)


@pytest.mark.qwen3_embedding
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_embedding_qwen3_embedding_get_model")
def test_embedding_qwen3_embedding_get_model(setup_logging) -> None:
    """test_embedding_qwen3_embedding_get_model"""
    _get_model_func("qwen3-embedding", setup_logging)


@pytest.mark.qwen3_forcealigner
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_qwen3_forcealigner_get_model")
def test_asr_qwen3_forcealigner_get_model(setup_logging) -> None:
    """test_asr_qwen3_forcealigner_get_model"""
    _get_model_func("qwen3-forcealigner", setup_logging)


@pytest.mark.qwen3_next
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_48g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_qwen3_next_get_model")
def test_llm_qwen3_next_get_model(setup_logging) -> None:
    """test_llm_qwen3_next_get_model"""
    _get_model_func("qwen3-next", setup_logging)


@pytest.mark.qwen3_omni
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_omni_qwen3_omni_get_model")
def test_omni_qwen3_omni_get_model(setup_logging) -> None:
    """test_omni_qwen3_omni_get_model"""
    _get_model_func("qwen3-omni", setup_logging)


@pytest.mark.qwen3_reranker
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_reranker_qwen3_reranker_get_model")
def test_reranker_qwen3_reranker_get_model(setup_logging) -> None:
    """test_reranker_qwen3_reranker_get_model"""
    _get_model_func("qwen3-reranker", setup_logging)


@pytest.mark.qwen3_tts
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_tts_qwen3_tts_get_model")
def test_tts_qwen3_tts_get_model(setup_logging) -> None:
    """test_tts_qwen3_tts_get_model"""
    _get_model_func("qwen3-tts", setup_logging)


@pytest.mark.qwen3_vl_embedding
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_embedding_qwen3_vl_embedding_get_model")
def test_embedding_qwen3_vl_embedding_get_model(setup_logging) -> None:
    """test_embedding_qwen3_vl_embedding_get_model"""
    _get_model_func("qwen3-vl-embedding", setup_logging)


@pytest.mark.qwen3_vl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_vlm_qwen3_vl_get_model")
def test_vlm_qwen3_vl_get_model(setup_logging) -> None:
    """test_vlm_qwen3_vl_get_model"""
    _get_model_func("qwen3-vl", setup_logging)


@pytest.mark.qwen3dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_qwen3dot5_get_model")
def test_llm_qwen3dot5_get_model(setup_logging) -> None:
    """test_llm_qwen3dot5_get_model"""
    _get_model_func("qwen3.5", setup_logging)


@pytest.mark.qwen3dot5_tool_test
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_qwen3dot5_tool_test_get_model")
def test_llm_qwen3dot5_tool_test_get_model(setup_logging) -> None:
    """test_llm_qwen3dot5_tool_test_get_model"""
    _get_model_func("qwen3.5_tool_test", setup_logging)


@pytest.mark.qwen3
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_llm_qwen3_get_model")
def test_llm_qwen3_get_model(setup_logging) -> None:
    """test_llm_qwen3_get_model"""
    _get_model_func("qwen3", setup_logging)


@pytest.mark.resnet50
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_backbone_resnet50_get_model")
def test_backbone_resnet50_get_model(setup_logging) -> None:
    """test_backbone_resnet50_get_model"""
    _get_model_func("resnet50", setup_logging)


@pytest.mark.sam2
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_segmentation_sam2_get_model")
def test_segmentation_sam2_get_model(setup_logging) -> None:
    """test_segmentation_sam2_get_model"""
    _get_model_func("sam2", setup_logging)


@pytest.mark.sdxl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_diffusion_sdxl_get_model")
def test_diffusion_sdxl_get_model(setup_logging) -> None:
    """test_diffusion_sdxl_get_model"""
    _get_model_func("sdxl", setup_logging)


@pytest.mark.sensevoice
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_sensevoice_get_model")
def test_asr_sensevoice_get_model(setup_logging) -> None:
    """test_asr_sensevoice_get_model"""
    _get_model_func("sensevoice", setup_logging)


@pytest.mark.siglip2
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_embedding_siglip2_get_model")
def test_embedding_siglip2_get_model(setup_logging) -> None:
    """test_embedding_siglip2_get_model"""
    _get_model_func("siglip2", setup_logging)


@pytest.mark.vit
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_backbone_vit_get_model")
def test_backbone_vit_get_model(setup_logging) -> None:
    """test_backbone_vit_get_model"""
    _get_model_func("vit", setup_logging)


@pytest.mark.wenet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_wenet_get_model")
def test_asr_wenet_get_model(setup_logging) -> None:
    """test_asr_wenet_get_model"""
    _get_model_func("wenet", setup_logging)


@pytest.mark.whisper
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_asr_whisper_get_model")
def test_asr_whisper_get_model(setup_logging) -> None:
    """test_asr_whisper_get_model"""
    _get_model_func("whisper", setup_logging)


@pytest.mark.yolo11m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolo11m_get_model")
def test_detection_yolo11m_get_model(setup_logging) -> None:
    """test_detection_yolo11m_get_model"""
    _get_model_func("yolo11m", setup_logging)


@pytest.mark.yolo12m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolo12m_get_model")
def test_detection_yolo12m_get_model(setup_logging) -> None:
    """test_detection_yolo12m_get_model"""
    _get_model_func("yolo12m", setup_logging)


@pytest.mark.yolo26m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolo26m_get_model")
def test_detection_yolo26m_get_model(setup_logging) -> None:
    """test_detection_yolo26m_get_model"""
    _get_model_func("yolo26m", setup_logging)


@pytest.mark.yolop
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_autodrive_yolop_get_model")
def test_autodrive_yolop_get_model(setup_logging) -> None:
    """test_autodrive_yolop_get_model"""
    _get_model_func("yolop", setup_logging)


@pytest.mark.yolov10m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolov10m_get_model")
def test_detection_yolov10m_get_model(setup_logging) -> None:
    """test_detection_yolov10m_get_model"""
    _get_model_func("yolov10m", setup_logging)


@pytest.mark.yolov3
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolov3_get_model")
def test_detection_yolov3_get_model(setup_logging) -> None:
    """test_detection_yolov3_get_model"""
    _get_model_func("yolov3", setup_logging)


@pytest.mark.yolov5m_face
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolov5m_face_get_model")
def test_detection_yolov5m_face_get_model(setup_logging) -> None:
    """test_detection_yolov5m_face_get_model"""
    _get_model_func("yolov5m_face", setup_logging)


@pytest.mark.yolov5s
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolov5s_get_model")
def test_detection_yolov5s_get_model(setup_logging) -> None:
    """test_detection_yolov5s_get_model"""
    _get_model_func("yolov5s", setup_logging)


@pytest.mark.yolov5s_feature
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolov5s_feature_get_model")
def test_detection_yolov5s_feature_get_model(setup_logging) -> None:
    """test_detection_yolov5s_feature_get_model"""
    _get_model_func("yolov5s_feature", setup_logging)


@pytest.mark.yolov7
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolov7_get_model")
def test_detection_yolov7_get_model(setup_logging) -> None:
    """test_detection_yolov7_get_model"""
    _get_model_func("yolov7", setup_logging)


@pytest.mark.yolov8m_cls
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_backbone_yolov8m_cls_get_model")
def test_backbone_yolov8m_cls_get_model(setup_logging) -> None:
    """test_backbone_yolov8m_cls_get_model"""
    _get_model_func("yolov8m-cls", setup_logging)


@pytest.mark.yolov8m_pose
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_estimation_yolov8m_pose_get_model")
def test_estimation_yolov8m_pose_get_model(setup_logging) -> None:
    """test_estimation_yolov8m_pose_get_model"""
    _get_model_func("yolov8m-pose", setup_logging)


@pytest.mark.yolov8m_seg
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_segmentation_yolov8m_seg_get_model")
def test_segmentation_yolov8m_seg_get_model(setup_logging) -> None:
    """test_segmentation_yolov8m_seg_get_model"""
    _get_model_func("yolov8m-seg", setup_logging)


@pytest.mark.yolov8m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolov8m_get_model")
def test_detection_yolov8m_get_model(setup_logging) -> None:
    """test_detection_yolov8m_get_model"""
    _get_model_func("yolov8m", setup_logging)


@pytest.mark.yolov9m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolov9m_get_model")
def test_detection_yolov9m_get_model(setup_logging) -> None:
    """test_detection_yolov9m_get_model"""
    _get_model_func("yolov9m", setup_logging)


@pytest.mark.yolox
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_detection_yolox_get_model")
def test_detection_yolox_get_model(setup_logging) -> None:
    """test_detection_yolox_get_model"""
    _get_model_func("yolox", setup_logging)


@pytest.mark.z_image_turbo
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.get_model
@pytest.mark.dependency(name="test_get_models.py::test_diffusion_z_image_turbo_get_model")
def test_diffusion_z_image_turbo_get_model(setup_logging) -> None:
    """test_diffusion_z_image_turbo_get_model"""
    _get_model_func("z-image-turbo", setup_logging)
