# Copyright (c) 2025 HOUMO AI
#
# File: test_perf_models.py
# Description:
#  Model Performance Tests Module.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Generated by update_test_py.py. Do not edit manually.

import logging

import pytest

from .test_models_utils import execute_perf_flow

logger = logging.getLogger(__name__)


def _perf_func(model_name: str, setup_logging) -> None:
    """Execute model performance test for a specific model."""
    logger.info("===> TEST START: test_%s_perf", model_name)
    execute_perf_flow(model_name, setup_logging)


@pytest.mark.copaw_flash
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_llm_copaw_flash_perf(setup_logging) -> None:
    """test_llm_copaw_flash_perf"""
    _perf_func("copaw-flash", setup_logging)


@pytest.mark.deepseek_r1_qwen3_8b
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_llm_deepseek_r1_qwen3_8b_perf(setup_logging) -> None:
    """test_llm_deepseek_r1_qwen3_8b_perf"""
    _perf_func("deepseek-r1-qwen3-8b", setup_logging)


@pytest.mark.deepseek
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_llm_deepseek_perf(setup_logging) -> None:
    """test_llm_deepseek_perf"""
    _perf_func("deepseek", setup_logging)


@pytest.mark.dinov3_base
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_backbone_dinov3_base_perf(setup_logging) -> None:
    """test_backbone_dinov3_base_perf"""
    _perf_func("dinov3-base", setup_logging)


@pytest.mark.efficientnet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_backbone_efficientnet_perf(setup_logging) -> None:
    """test_backbone_efficientnet_perf"""
    _perf_func("efficientnet", setup_logging)


@pytest.mark.glm_ocr
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_ocr_glm_ocr_perf(setup_logging) -> None:
    """test_ocr_glm_ocr_perf"""
    _perf_func("glm-ocr", setup_logging)


@pytest.mark.gpt_oss
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.perf
def test_llm_gpt_oss_perf(setup_logging) -> None:
    """test_llm_gpt_oss_perf"""
    _perf_func("gpt-oss", setup_logging)


@pytest.mark.gte
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_embedding_gte_perf(setup_logging) -> None:
    """test_embedding_gte_perf"""
    _perf_func("gte", setup_logging)


@pytest.mark.lprnet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_ocr_lprnet_perf(setup_logging) -> None:
    """test_ocr_lprnet_perf"""
    _perf_func("lprnet", setup_logging)


@pytest.mark.mobilenetv2
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_backbone_mobilenetv2_perf(setup_logging) -> None:
    """test_backbone_mobilenetv2_perf"""
    _perf_func("mobilenetv2", setup_logging)


@pytest.mark.ppocrv3_det
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_ocr_ppocrv3_det_perf(setup_logging) -> None:
    """test_ocr_ppocrv3_det_perf"""
    _perf_func("ppocrv3_det", setup_logging)


@pytest.mark.ppocrv3_rec
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_ocr_ppocrv3_rec_perf(setup_logging) -> None:
    """test_ocr_ppocrv3_rec_perf"""
    _perf_func("ppocrv3_rec", setup_logging)


@pytest.mark.qwen_agentworld
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.perf
def test_llm_qwen_agentworld_perf(setup_logging) -> None:
    """test_llm_qwen_agentworld_perf"""
    _perf_func("qwen-agentworld", setup_logging)


@pytest.mark.qwen2dot5_vl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_vlm_qwen2dot5_vl_perf(setup_logging) -> None:
    """test_vlm_qwen2dot5_vl_perf"""
    _perf_func("qwen2.5-vl", setup_logging)


@pytest.mark.qwen2dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_llm_qwen2dot5_perf(setup_logging) -> None:
    """test_llm_qwen2dot5_perf"""
    _perf_func("qwen2.5", setup_logging)


@pytest.mark.qwen3_30b_a3b
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.perf
def test_llm_qwen3_30b_a3b_perf(setup_logging) -> None:
    """test_llm_qwen3_30b_a3b_perf"""
    _perf_func("qwen3-30b-a3b", setup_logging)


@pytest.mark.qwen3_asr
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_asr_qwen3_asr_perf(setup_logging) -> None:
    """test_asr_qwen3_asr_perf"""
    _perf_func("qwen3-asr", setup_logging)


@pytest.mark.qwen3_next
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_48g
@pytest.mark.perf
def test_llm_qwen3_next_perf(setup_logging) -> None:
    """test_llm_qwen3_next_perf"""
    _perf_func("qwen3-next", setup_logging)


@pytest.mark.qwen3_reranker
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_reranker_qwen3_reranker_perf(setup_logging) -> None:
    """test_reranker_qwen3_reranker_perf"""
    _perf_func("qwen3-reranker", setup_logging)


@pytest.mark.qwen3_vl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_vlm_qwen3_vl_perf(setup_logging) -> None:
    """test_vlm_qwen3_vl_perf"""
    _perf_func("qwen3-vl", setup_logging)


@pytest.mark.qwen3dot5
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.perf
def test_llm_qwen3dot5_perf(setup_logging) -> None:
    """test_llm_qwen3dot5_perf"""
    _perf_func("qwen3.5", setup_logging)


@pytest.mark.qwen3
@pytest.mark.ndevice_2
@pytest.mark.dev_mem_24g
@pytest.mark.perf
def test_llm_qwen3_perf(setup_logging) -> None:
    """test_llm_qwen3_perf"""
    _perf_func("qwen3", setup_logging)


@pytest.mark.resnet50
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_backbone_resnet50_perf(setup_logging) -> None:
    """test_backbone_resnet50_perf"""
    _perf_func("resnet50", setup_logging)


@pytest.mark.sdxl
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_diffusion_sdxl_perf(setup_logging) -> None:
    """test_diffusion_sdxl_perf"""
    _perf_func("sdxl", setup_logging)


@pytest.mark.vit
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_backbone_vit_perf(setup_logging) -> None:
    """test_backbone_vit_perf"""
    _perf_func("vit", setup_logging)


@pytest.mark.wenet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_asr_wenet_perf(setup_logging) -> None:
    """test_asr_wenet_perf"""
    _perf_func("wenet", setup_logging)


@pytest.mark.whisper
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_asr_whisper_perf(setup_logging) -> None:
    """test_asr_whisper_perf"""
    _perf_func("whisper", setup_logging)


@pytest.mark.yolo11m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolo11m_perf(setup_logging) -> None:
    """test_detection_yolo11m_perf"""
    _perf_func("yolo11m", setup_logging)


@pytest.mark.yolo12m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolo12m_perf(setup_logging) -> None:
    """test_detection_yolo12m_perf"""
    _perf_func("yolo12m", setup_logging)


@pytest.mark.yolo26m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolo26m_perf(setup_logging) -> None:
    """test_detection_yolo26m_perf"""
    _perf_func("yolo26m", setup_logging)


@pytest.mark.yolop
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_autodrive_yolop_perf(setup_logging) -> None:
    """test_autodrive_yolop_perf"""
    _perf_func("yolop", setup_logging)


@pytest.mark.yolov10m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolov10m_perf(setup_logging) -> None:
    """test_detection_yolov10m_perf"""
    _perf_func("yolov10m", setup_logging)


@pytest.mark.yolov3
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolov3_perf(setup_logging) -> None:
    """test_detection_yolov3_perf"""
    _perf_func("yolov3", setup_logging)


@pytest.mark.yolov5m_face
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolov5m_face_perf(setup_logging) -> None:
    """test_detection_yolov5m_face_perf"""
    _perf_func("yolov5m_face", setup_logging)


@pytest.mark.yolov5s
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolov5s_perf(setup_logging) -> None:
    """test_detection_yolov5s_perf"""
    _perf_func("yolov5s", setup_logging)


@pytest.mark.yolov5s_feature
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolov5s_feature_perf(setup_logging) -> None:
    """test_detection_yolov5s_feature_perf"""
    _perf_func("yolov5s_feature", setup_logging)


@pytest.mark.yolov7
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolov7_perf(setup_logging) -> None:
    """test_detection_yolov7_perf"""
    _perf_func("yolov7", setup_logging)


@pytest.mark.yolov8m_cls
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_backbone_yolov8m_cls_perf(setup_logging) -> None:
    """test_backbone_yolov8m_cls_perf"""
    _perf_func("yolov8m-cls", setup_logging)


@pytest.mark.yolov8m_pose
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_estimation_yolov8m_pose_perf(setup_logging) -> None:
    """test_estimation_yolov8m_pose_perf"""
    _perf_func("yolov8m-pose", setup_logging)


@pytest.mark.yolov8m_seg
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_segmentation_yolov8m_seg_perf(setup_logging) -> None:
    """test_segmentation_yolov8m_seg_perf"""
    _perf_func("yolov8m-seg", setup_logging)


@pytest.mark.yolov8m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolov8m_perf(setup_logging) -> None:
    """test_detection_yolov8m_perf"""
    _perf_func("yolov8m", setup_logging)


@pytest.mark.yolov9m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolov9m_perf(setup_logging) -> None:
    """test_detection_yolov9m_perf"""
    _perf_func("yolov9m", setup_logging)


@pytest.mark.yolox
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.perf
def test_detection_yolox_perf(setup_logging) -> None:
    """test_detection_yolox_perf"""
    _perf_func("yolox", setup_logging)


@pytest.mark.qwen_agentworld
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_24g
@pytest.mark.perf
def test_qwen_agentworld_perf(setup_logging) -> None:
    """test_qwen_agentworld_perf"""
    _perf_func("qwen-agentworld", setup_logging)
