# Copyright (c) 2025 HOUMO AI
#
# File: test_compare_models.py
# Description:
#  Model Comparison Tests Module.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Generated by update_test_py.py. Do not edit manually.

import logging

import pytest

from .test_models_utils import execute_compare_flow

logger = logging.getLogger(__name__)


def _compare_func(model_name: str, setup_logging) -> None:
    """Execute model comparison test for a specific model."""
    logger.info("===> TEST START: test_%s_compare", model_name)
    execute_compare_flow(model_name, setup_logging)


@pytest.mark.efficientnet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_backbone_efficientnet_compare(setup_logging) -> None:
    """test_backbone_efficientnet_compare"""
    _compare_func("efficientnet", setup_logging)


@pytest.mark.lprnet
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_ocr_lprnet_compare(setup_logging) -> None:
    """test_ocr_lprnet_compare"""
    _compare_func("lprnet", setup_logging)


@pytest.mark.mobilenetv2
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_backbone_mobilenetv2_compare(setup_logging) -> None:
    """test_backbone_mobilenetv2_compare"""
    _compare_func("mobilenetv2", setup_logging)


@pytest.mark.ppocrv3_det
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_ocr_ppocrv3_det_compare(setup_logging) -> None:
    """test_ocr_ppocrv3_det_compare"""
    _compare_func("ppocrv3_det", setup_logging)


@pytest.mark.ppocrv3_rec
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_ocr_ppocrv3_rec_compare(setup_logging) -> None:
    """test_ocr_ppocrv3_rec_compare"""
    _compare_func("ppocrv3_rec", setup_logging)


@pytest.mark.resnet50
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_backbone_resnet50_compare(setup_logging) -> None:
    """test_backbone_resnet50_compare"""
    _compare_func("resnet50", setup_logging)


@pytest.mark.vit
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_backbone_vit_compare(setup_logging) -> None:
    """test_backbone_vit_compare"""
    _compare_func("vit", setup_logging)


@pytest.mark.yolo11m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolo11m_compare(setup_logging) -> None:
    """test_detection_yolo11m_compare"""
    _compare_func("yolo11m", setup_logging)


@pytest.mark.yolo12m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolo12m_compare(setup_logging) -> None:
    """test_detection_yolo12m_compare"""
    _compare_func("yolo12m", setup_logging)


@pytest.mark.yolo26m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolo26m_compare(setup_logging) -> None:
    """test_detection_yolo26m_compare"""
    _compare_func("yolo26m", setup_logging)


@pytest.mark.yolop
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_autodrive_yolop_compare(setup_logging) -> None:
    """test_autodrive_yolop_compare"""
    _compare_func("yolop", setup_logging)


@pytest.mark.yolov10m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolov10m_compare(setup_logging) -> None:
    """test_detection_yolov10m_compare"""
    _compare_func("yolov10m", setup_logging)


@pytest.mark.yolov3
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolov3_compare(setup_logging) -> None:
    """test_detection_yolov3_compare"""
    _compare_func("yolov3", setup_logging)


@pytest.mark.yolov5m_face
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolov5m_face_compare(setup_logging) -> None:
    """test_detection_yolov5m_face_compare"""
    _compare_func("yolov5m_face", setup_logging)


@pytest.mark.yolov5s
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolov5s_compare(setup_logging) -> None:
    """test_detection_yolov5s_compare"""
    _compare_func("yolov5s", setup_logging)


@pytest.mark.yolov5s_feature
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolov5s_feature_compare(setup_logging) -> None:
    """test_detection_yolov5s_feature_compare"""
    _compare_func("yolov5s_feature", setup_logging)


@pytest.mark.yolov7
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolov7_compare(setup_logging) -> None:
    """test_detection_yolov7_compare"""
    _compare_func("yolov7", setup_logging)


@pytest.mark.yolov8m_cls
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_backbone_yolov8m_cls_compare(setup_logging) -> None:
    """test_backbone_yolov8m_cls_compare"""
    _compare_func("yolov8m-cls", setup_logging)


@pytest.mark.yolov8m_pose
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_estimation_yolov8m_pose_compare(setup_logging) -> None:
    """test_estimation_yolov8m_pose_compare"""
    _compare_func("yolov8m-pose", setup_logging)


@pytest.mark.yolov8m_seg
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_segmentation_yolov8m_seg_compare(setup_logging) -> None:
    """test_segmentation_yolov8m_seg_compare"""
    _compare_func("yolov8m-seg", setup_logging)


@pytest.mark.yolov8m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolov8m_compare(setup_logging) -> None:
    """test_detection_yolov8m_compare"""
    _compare_func("yolov8m", setup_logging)


@pytest.mark.yolov9m
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolov9m_compare(setup_logging) -> None:
    """test_detection_yolov9m_compare"""
    _compare_func("yolov9m", setup_logging)


@pytest.mark.yolox
@pytest.mark.ndevice_1
@pytest.mark.dev_mem_12g
@pytest.mark.compare
def test_detection_yolox_compare(setup_logging) -> None:
    """test_detection_yolox_compare"""
    _compare_func("yolox", setup_logging)
