# Linux platform configuration for houmo_infer.

set(HOUMO_PLATFORM_NAME "linux")
set(HOUMO_NEED_PTHREAD TRUE)
set(HOUMO_CXX17_FLAG "-std=c++17")
set(HOUMO_COMPILE_OPTIONS -Wno-deprecated-declarations)
set(HOUMO_RELEASE_FLAGS "-O3 -DNDEBUG -DEIGEN_MPL2_ONLY")
set(HOUMO_DEBUG_FLAGS "-g -O0 -ggdb")
set(HOUMO_EXPORT_ALL_SYMBOLS FALSE)
set(HOUMO_TARGET_LINK_OPTIONS "")

execute_process(
  COMMAND uname -m
  OUTPUT_VARIABLE ARCH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(HOUMO_TARGET "$ENV{HOUMO_TARGET}")
set(LIB_PATH "Linux_${ARCH}_${HOUMO_TARGET}")

if(DEFINED ENV{HOUMO_EXAMPLES_PATH})
  set(LIB_INSTALL_PATH "$ENV{HOUMO_EXAMPLES_PATH}/utils/lib")
endif()
