# Windows platform configuration for houmo_infer.

set(HOUMO_PLATFORM_NAME "windows")
set(HOUMO_NEED_PTHREAD FALSE)
set(HOUMO_CXX17_FLAG "/std:c++17")
set(HOUMO_COMPILE_OPTIONS /utf-8 /wd4996)
set(HOUMO_RELEASE_FLAGS "/O2 /DNDEBUG")
set(HOUMO_DEBUG_FLAGS "")
set(HOUMO_EXPORT_ALL_SYMBOLS TRUE)
set(HOUMO_TARGET_LINK_OPTIONS /IGNORE:4197)

if(DEFINED ENV{HOUMO_EXAMPLES_PATH})
  set(LIB_INSTALL_PATH "$ENV{HOUMO_EXAMPLES_PATH}/utils/lib")
endif()
