cmake_minimum_required(VERSION 3.16.3)
project(itvm_example)

set(TCIM_PATH $ENV{TCIM_PATH})
set(HDPL_TOOLCHAIN_ITVM_INSTALL $ENV{HOUMO_PATH})

unset(TVM_LIBRARY CACHE)
if(DEFINED ENV{HDPL_TOOLCHAIN_ITVM_INSTALL})
  message(STATUS "HDPL_TOOLCHAIN_ITVM_INSTALL: " $ENV{HDPL_TOOLCHAIN_ITVM_INSTALL})
  set(HDPL_TOOLCHAIN_ITVM_INSTALL $ENV{HDPL_TOOLCHAIN_ITVM_INSTALL})
endif()
find_library(TVM_LIBRARY NAMES tvm PATHS ${TCIM_PATH} NO_DEFAULT_PATH)
if(NOT DEFINED ${TVM_LIBRARY})
  find_library(TVM_LIBRARY NAMES tvm PATHS ${TCIM_PATH}/lib NO_DEFAULT_PATH)
endif()
include_directories(${HDPL_TOOLCHAIN_ITVM_INSTALL}/include)
message(STATUS "HDPL_TOOLCHAIN DIR: ${HDPL_TOOLCHAIN_ITVM_INSTALL}")

include_directories(${TCIM_PATH}/include)

add_definitions(-w)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -O2")
add_executable(hdpl_cruise_go_vehicle_run hdpl_cruise_go_vehicle_run.cc)
target_link_libraries(hdpl_cruise_go_vehicle_run ${OpenCV_LIBS})
target_link_libraries(hdpl_cruise_go_vehicle_run ${TVM_LIBRARY} -pthread dl gomp)
