Streams:
default_model_name: "qwen2.5-vl"
default_model_size: "7b"

model_configs:
  qwen2.5-vl:
    "7b":
      modelscope_repo: ["Qwen/Qwen2.5-VL-7B-Instruct"]
      model_name: "qwen2.5-vl"
      model_size: "7b"
      ncore: 2
      quant_type: "w4a8h1_ssfp"
      context_length: "8k"
      ndevice: 1
      batch: 1
      prefill_length: 256
      max_size_w: 448
      max_size_h: 448
      max_size_t: 2