# Copyright (c) 2025 HOUMO AI
#
# File: artifact_file_scanner.py
# Description:
#  Artifact File Discovery and Compiler Intermediate Pruning.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Identify non-empty model outputs and remove compiler-only intermediates."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Iterable, Sequence

logger = logging.getLogger(__name__)


__all__ = [
    "build_required_file_roles",
    "find_nonempty_artifact_files",
    "find_nonempty_hmm_files",
    "prune_compiler_intermediates",
]


def find_nonempty_artifact_files(
    directory: Path,
    *,
    patterns: Iterable[str] = ("*",),
    limit: int | None = None,
) -> list[Path]:
    """Return stable non-empty artifact files, excluding cache metadata."""
    if not directory.is_dir():
        return []
    files = sorted({
        path
        for pattern in patterns
        for path in directory.rglob(pattern)
        if path.is_file()
        and path.stat().st_size > 0
        and path.name != "lock.lock"
        and not path.name.startswith("artifact_manifest")
        and ".partial-" not in path.name
    })
    return files if limit is None else files[:limit]


def find_nonempty_hmm_files(directory: Path) -> list[Path]:
    """Return stable non-empty HMM files under an artifact directory."""
    return find_nonempty_artifact_files(
        directory,
        patterns=("*.hmm", "*.hmms"),
    )


def build_required_file_roles(
    directory: Path, files: Iterable[Path], *, prefix: str
) -> dict[str, str]:
    """Map artifact files to stable manifest roles relative to their directory."""
    return {
        f"{prefix}_{index}": str(path.relative_to(directory))
        for index, path in enumerate(files)
    }


COMPILER_INTERMEDIATE_DIR = "tcim"
COMPILER_INTERMEDIATE_KEEP_SUFFIXES = (".json", ".cpp")


def prune_compiler_intermediates(
    directory: Path,
    *,
    keep_suffixes: Sequence[str] = COMPILER_INTERMEDIATE_KEEP_SUFFIXES,
) -> int:
    """Delete regenerable compiler intermediates under ``tcim`` directories.

    The compiler keeps its whole working tree beside the published ``.hmm``
    files. Only the model description (``.json``) and the generated source
    (``.cpp``) carry diagnostic value; everything else can be regenerated by
    recompiling and accounts for the bulk of the result cache.

    Must run *before* the manifest is written: :meth:`ArtifactCache.inspect`
    treats a missing ``required_files`` entry as ``CORRUPTED``, so pruning after
    publication would risk a cache that permanently invalidates itself.

    Matching uses the final suffix only. Intermediates such as
    ``model.cpp.o`` or ``model.cpp.hdpl.lib.a`` contain ``.cpp`` in their name
    without being C++ sources, and a substring test would keep nearly
    everything.
    """
    if not directory.is_dir():
        return 0
    kept = tuple(keep_suffixes)
    released = 0
    for intermediate_dir in sorted(directory.rglob(COMPILER_INTERMEDIATE_DIR)):
        if not intermediate_dir.is_dir():
            continue
        for path in sorted(intermediate_dir.rglob("*")):
            released += _prune_intermediate_file(path, kept)
        _remove_empty_directories(intermediate_dir)
    if released:
        logger.info(
            "Pruned %.2f MB of compiler intermediates under %s",
            released / (1024 * 1024),
            directory,
        )
    return released


def _prune_intermediate_file(path: Path, keep_suffixes: Sequence[str]) -> int:
    """Remove one regenerable compiler file and return its released bytes."""
    if not path.is_file() or path.is_symlink() or path.suffix in keep_suffixes:
        return 0
    try:
        size = path.stat().st_size
        path.unlink()
    except OSError as error:
        logger.warning("Failed to prune intermediate %s: %s", path, error)
        return 0
    return size


def _remove_empty_directories(root: Path) -> None:
    """Remove directories left empty by pruning, deepest first."""
    for path in sorted(root.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        if not path.is_dir():
            continue
        try:
            path.rmdir()
        except OSError:
            continue
